# Generated by Django 5.1.3 on 2026-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionparticipant",
            name="source",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("manual", "Manual"),
                    ("student_request", "Student Request"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessionparticipant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("booked", "Booked"),
                    ("attended", "Attended"),
                    ("no_show", "NoShow"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
