# Generated by Django 5.1.3 on 2026-02-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_sessionparticipant_source_and_more"),
        ("core", "0004_add_clinic_idcard_colors"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionparticipant",
            name="uniq_clinic_participant_per_tenant",
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="requested_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="requested_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessionparticipant",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="clinic.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("tenant", "session", "student"),
                name="uniq_clinic_participant_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", True)),
                fields=("tenant", "requested_date", "requested_start_time", "student"),
                name="uniq_clinic_participant_request_per_tenant",
            ),
        ),
    ]
