# Generated by Django 5.1.3 on 2026-03-11 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clinic",
            "0004_remove_sessionparticipant_uniq_clinic_participant_per_tenant_and_more",
        ),
        ("core", "0013_add_own_messaging_credentials"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="uniq_clinic_session_per_tenant_time_location",
        ),
        migrations.AddField(
            model_name="session",
            name="target_grade",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1학년"), (2, "2학년"), (3, "3학년")],
                help_text="대상 학년. 비어있으면 전체 학년.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_grade__isnull", False)),
                fields=("tenant", "date", "start_time", "location", "target_grade"),
                name="uniq_clinic_session_per_tenant_time_loc_grade",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_grade__isnull", True)),
                fields=("tenant", "date", "start_time", "location"),
                name="uniq_clinic_session_per_tenant_time_location",
            ),
        ),
    ]
