# Generated by Django 5.1.3 on 2026-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_add_title_target_grade_to_session"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="target_lectures",
            field=models.ManyToManyField(
                blank=True,
                help_text="대상 강의. 비어있으면 전체 학생.",
                related_name="clinic_sessions",
                to="lectures.lecture",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="target_school_type",
            field=models.CharField(
                blank=True,
                choices=[("MIDDLE", "중등"), ("HIGH", "고등")],
                help_text="대상 학교 유형. 비어있으면 전체.",
                max_length=10,
                null=True,
            ),
        ),
    ]
