# Generated by Django 5.1.3 on 2026-03-15 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_add_target_school_type_and_lectures"),
        ("core", "0022_program_legal_fields"),
        ("students", "0008_tag_tenant_isolation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionparticipant",
            name="uniq_clinic_participant_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="sessionparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("session__isnull", False), ("status__in", ["pending", "booked"])
                ),
                fields=("tenant", "session", "student"),
                name="uniq_clinic_participant_active",
            ),
        ),
    ]
