# Generated by Django 5.2.9 on 2026-02-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_add_tenant_to_clinic_domain"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionparticipant",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
    ]
