# Generated by Django 5.1.3 on 2026-03-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_add_completed_fields"),
        ("enrollment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionparticipant",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_participations",
                to="enrollment.enrollment",
            ),
        ),
    ]
