# Generated by Django 5.1.3 on 2026-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0010_alter_sessionparticipant_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="target_grade",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1학년"),
                    (2, "2학년"),
                    (3, "3학년"),
                    (4, "4학년"),
                    (5, "5학년"),
                    (6, "6학년"),
                ],
                help_text="대상 학년. 비어있으면 전체 학년.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="target_school_type",
            field=models.CharField(
                blank=True,
                choices=[("ELEMENTARY", "초등"), ("MIDDLE", "중등"), ("HIGH", "고등")],
                help_text="대상 학교 유형. 비어있으면 전체.",
                max_length=10,
                null=True,
            ),
        ),
    ]
