# Generated by Django 5.1.3 on 2026-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0011_school_level_mode_elementary"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="memo",
            field=models.TextField(
                blank=True, default="", help_text="세션 메모 (운영용)"
            ),
        ),
    ]
