# Generated by Django 5.1.3 on 2026-04-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0012_add_memo_to_session"),
        ("lectures", "0006_p0_attempt_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="대상 반. section_mode에서만 사용. 비어있으면 전체.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_sessions",
                to="lectures.section",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="target_lectures",
            field=models.ManyToManyField(
                blank=True,
                help_text="대상 강의. 비어있으면 전체 학생.",
                related_name="clinic_sessions_by_lecture",
                to="lectures.lecture",
            ),
        ),
    ]
