# Generated by Django 5.2.16 on 2026-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_sessionparticipant_completion_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booking_interval_minutes',
            field=models.PositiveSmallIntegerField(db_default=60, default=60, help_text='시간 범위 예약의 선택 간격 스냅샷입니다.'),
        ),
        migrations.AddField(
            model_name='session',
            name='booking_max_stay_minutes',
            field=models.PositiveIntegerField(db_default=240, default=240, help_text='시간 범위 예약의 최대 체류 분 스냅샷입니다.'),
        ),
        migrations.AddField(
            model_name='session',
            name='booking_mode',
            field=models.CharField(choices=[('fixed_slot', '고정 시간대'), ('time_range', '시간 범위')], db_default='fixed_slot', default='fixed_slot', help_text='세션 생성 시 고정된 예약 방식 스냅샷입니다.', max_length=16),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='booking_end_time',
            field=models.TimeField(blank=True, help_text='시간 범위 방식에서 확정된 실제 예약 종료 시각입니다.', null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='booking_start_time',
            field=models.TimeField(blank=True, help_text='시간 범위 방식에서 확정된 실제 예약 시작 시각입니다.', null=True),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('booking_mode__in', ('fixed_slot', 'time_range'))), name='clinic_session_booking_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('booking_interval_minutes__in', (30, 60))), name='clinic_session_booking_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('booking_max_stay_minutes__gte', models.F('booking_interval_minutes'))), name='clinic_session_booking_stay_gte_interval'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking_end_time__isnull', True), ('booking_start_time__isnull', True)), models.Q(('booking_end_time__isnull', False), ('booking_start_time__isnull', False)), _connector='OR'), name='clinic_participant_booking_range_pair'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('booking_start_time__isnull', True), ('booking_start_time__lt', models.F('booking_end_time')), _connector='OR'), name='clinic_participant_booking_range_order'),
        ),
    ]
