# Generated by Django 5.1.3 on 2026-04-16 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0032_user_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchupDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(blank=True, default="", max_length=100)),
                (
                    "grade_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "r2_key",
                    models.CharField(db_index=True, max_length=512, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(default="application/pdf", max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_job_id", models.CharField(blank=True, default="", max_length=36)),
                ("problem_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchup_documents",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchupProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField(blank=True, default="")),
                ("image_key", models.CharField(blank=True, default="", max_length=512)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="matchup.matchupdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchup_problems",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("document", "number")},
            },
        ),
    ]
