# Generated by Django 5.1.3 on 2026-04-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchupproblem",
            name="source_exam_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="matchupproblem",
            name="source_exam_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matchupproblem",
            name="source_lecture_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matchupproblem",
            name="source_question_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchupproblem",
            name="source_session_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matchupproblem",
            name="source_type",
            field=models.CharField(
                choices=[("matchup", "매치업 업로드"), ("exam", "시험 문제")],
                db_index=True,
                default="matchup",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="matchupproblem",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="matchup.matchupdocument",
            ),
        ),
    ]
