# Generated by Django 5.1.3 on 2026-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_user_token_version"),
        ("matchup", "0002_matchupproblem_source_exam_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchupproblem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="matchupproblem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("document", "number"),
                name="unique_matchup_doc_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchupproblem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "exam")),
                fields=("tenant", "source_exam_id", "source_question_number"),
                name="unique_matchup_exam_question",
            ),
        ),
    ]
