# Generated by Django 5.1.3 on 2026-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchup", "0008_matchupdocument_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchupproblem",
            name="image_embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
