# Generated by Django 5.1.3 on 2026-05-02 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchup", "0011_author_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchupdocument",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="자료 업로더(소유 강사). NULL=legacy 공용 풀.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matchup_documents_authored",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="matchuphitreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="matchuphitreportentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
