# Generated by Django 5.1.3 on 2026-05-06 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # core 0036은 다른 세션 미커밋 영역 — Stage 3는 그것과 분리하여
        # core 의 prod 최신 (0035_workerheartbeatmodel)을 명시 dep로 사용.
        ("core", "0035_workerheartbeatmodel"),
        ("matchup", "0017_matchuphitreportentry_last_modified_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemSegmentationProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_version_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("page_number", models.IntegerField(db_index=True, default=0)),
                ("bbox", models.JSONField(blank=True, default=dict)),
                ("detected_problem_number", models.IntegerField(default=0)),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("yolo", "YOLO segmentation"),
                            ("vlm", "VLM (Gemini)"),
                            ("ocr", "OCR + layout heuristic"),
                            ("native_pdf", "Native PDF parser"),
                            ("manual_assist", "사용자 수동 자르기 보조"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "검수 대기"),
                            ("needs_review", "검수 필수"),
                            ("rejected", "거절"),
                            ("approved", "승인 완료"),
                            ("auto_passed", "자동 통과 (validator)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("image_key", models.CharField(blank=True, default="", max_length=512)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_proposals",
                        to="matchup.matchupdocument",
                    ),
                ),
                (
                    "promoted_problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_proposals",
                        to="matchup.matchupproblem",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_segmentation_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchup_segmentation_proposals",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "page_number", "detected_problem_number"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "document", "status"],
                        name="matchup_pro_tenant__f48b8f_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status", "engine"],
                        name="matchup_pro_tenant__e886d5_idx",
                    ),
                    models.Index(
                        fields=["analysis_version_key"],
                        name="matchup_pro_analysi_c788e6_idx",
                    ),
                ],
            },
        ),
    ]
