# Generated by Django 5.1.3 on 2026-05-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # core 0036 은 다른 세션 미커밋 영역 — 0019 는 prod 적용된 core 0035 로 명시 dep.
        ("core", "0035_workerheartbeatmodel"),
        ("matchup", "0018_problemsegmentationproposal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("fingerprint_version", models.PositiveIntegerField(default=1)),
                ("page_count", models.IntegerField(default=0)),
                ("page_size", models.JSONField(blank=True, default=dict)),
                ("text_density", models.FloatField(default=0.0)),
                ("image_density", models.FloatField(default=0.0)),
                ("column_count", models.IntegerField(default=1)),
                ("anchor_density", models.FloatField(default=0.0)),
                ("x0_clusters", models.JSONField(blank=True, default=list)),
                ("y_gap_distribution", models.JSONField(blank=True, default=dict)),
                ("font_size_distribution", models.JSONField(blank=True, default=dict)),
                ("filename_patterns", models.JSONField(blank=True, default=list)),
                (
                    "similarity_cluster_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_fingerprints",
                        to="matchup.matchupdocument",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_fingerprints",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "paper_type"],
                        name="matchup_lay_tenant__2fe27c_idx",
                    ),
                    models.Index(
                        fields=["tenant", "similarity_cluster_id"],
                        name="matchup_lay_tenant__415678_idx",
                    ),
                    models.Index(
                        fields=["tenant", "document", "fingerprint_version"],
                        name="matchup_lay_tenant__7e747d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "document", "fingerprint_version"),
                        name="uniq_layout_fingerprint_per_doc_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ManualCorrectionDelta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("approve", "approve"),
                            ("reject", "reject"),
                            ("bbox_adjust", "bbox_adjust"),
                            ("split", "split"),
                            ("merge", "merge"),
                            ("manual_create", "manual_create"),
                            ("number_adjust", "number_adjust"),
                            ("text_adjust", "text_adjust"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_ui", "user_ui"),
                            ("admin_review", "admin_review"),
                        ],
                        default="user_ui",
                        max_length=16,
                    ),
                ),
                ("original_bbox", models.JSONField(blank=True, null=True)),
                ("corrected_bbox", models.JSONField(blank=True, null=True)),
                ("iou_with_ai", models.FloatField(blank=True, null=True)),
                (
                    "paper_type_at_action",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "engine_at_action",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchup_correction_deltas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_deltas",
                        to="matchup.matchupdocument",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_deltas",
                        to="matchup.matchupproblem",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_deltas",
                        to="matchup.problemsegmentationproposal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_correction_deltas",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "correction_type", "created_at"],
                        name="matchup_man_tenant__65f0df_idx",
                    ),
                    models.Index(
                        fields=["tenant", "paper_type_at_action"],
                        name="matchup_man_tenant__5d786b_idx",
                    ),
                    models.Index(
                        fields=["tenant", "document"],
                        name="matchup_man_tenant__501079_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantSegmentationProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("fallback_to_global", models.BooleanField(default=True)),
                ("profile_version", models.PositiveIntegerField(default=1)),
                ("paper_type_thresholds", models.JSONField(blank=True, default=dict)),
                ("paper_type_expected_max", models.JSONField(blank=True, default=dict)),
                ("auto_approve_thresholds", models.JSONField(blank=True, default=dict)),
                ("common_layout_clusters", models.JSONField(blank=True, default=list)),
                ("bbox_stats", models.JSONField(blank=True, default=dict)),
                (
                    "column_count_distribution",
                    models.JSONField(blank=True, default=dict),
                ),
                ("scanned_pdf_ratio", models.FloatField(blank=True, null=True)),
                ("manual_correction_rate", models.FloatField(blank=True, null=True)),
                ("vlm_needed_ratio", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("samples_used", models.IntegerField(default=0)),
                ("last_profiled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentation_profile",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="matchup_ten_tenant__e325f3_idx",
                    )
                ],
            },
        ),
    ]
