# Generated by Django 5.1.3 on 2026-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchup", "0021_autosegmentationsnapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="autosegmentationsnapshot",
            new_name="matchup_aut_tenant__e95a85_idx",
            old_name="matchup_aut_tenant__page_idx",
        ),
        migrations.RenameIndex(
            model_name="autosegmentationsnapshot",
            new_name="matchup_aut_tenant__5afff8_idx",
            old_name="matchup_aut_tenant__engine_idx",
        ),
        migrations.RenameIndex(
            model_name="autosegmentationsnapshot",
            new_name="matchup_aut_job_id_e018ca_idx",
            old_name="matchup_aut_job_id_idx",
        ),
        migrations.RenameIndex(
            model_name="matchuppagestate",
            new_name="matchup_mat_tenant__09540b_idx",
            old_name="matchup_pag_tenant__page_idx",
        ),
        migrations.RenameIndex(
            model_name="matchuppagestate",
            new_name="matchup_mat_tenant__dca325_idx",
            old_name="matchup_pag_tenant__state_idx",
        ),
        migrations.AddField(
            model_name="matchuphitreport",
            name="share_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
