# Generated by Django 5.1.3 on 2026-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchup", "0022_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchupdocument",
            name="exam_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "미지정"),
                    ("midterm", "중간고사"),
                    ("final", "기말고사"),
                    ("mock", "모의고사"),
                    ("other", "기타"),
                ],
                db_index=True,
                default="",
                help_text="시험 회차 분류 (랜딩 학교별 grouping)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="matchupdocument",
            name="exam_year",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="시험 연도 (예: 2025). 0=미지정. 학교별 grouping 시간순 정렬.",
            ),
        ),
    ]
