# Generated by Django 5.2.16 on 2026-09-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_tenant_clinic_use_daily_random_default'),
        ('matchup', '0023_matchupdocument_exam_cycle_matchupdocument_exam_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchupArtifactScanIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_id', models.PositiveBigIntegerField()),
                ('job_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('cleaned', 'Cleaned')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'matchup_artifact_scan_intent',
                'indexes': [models.Index(fields=['status', 'last_attempt_at'], name='matchup_scan_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'document_id', 'job_id'), name='uniq_matchup_scan_tenant_doc_job')],
            },
        ),
    ]
