# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "lecture_time",
                    models.CharField(
                        blank=True,
                        help_text="강의 시간 (예: 토 12:00 ~ 13:00)",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6", help_text="아이콘/라벨 색상", max_length=20
                    ),
                ),
                (
                    "chip_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="강의딱지 2글자 (미입력 시 제목 앞 2자 사용)",
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lectures.lecture",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["tenant", "created_at"], name="lectures_le_tenant__ca19dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("tenant", "title"), name="uniq_lecture_title_per_tenant"
            ),
        ),
    ]
