# Generated by Django 5.2.9 on 2026-01-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="exam",
        ),
    ]
