# Generated by Django 5.1.3 on 2026-04-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_set_dnb_school_level_mode"),
        ("enrollment", "0001_initial"),
        ("lectures", "0002_lecture_is_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(help_text="반 이름 (A, B, C...)", max_length=10),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[("CLASS", "수업"), ("CLINIC", "클리닉")],
                        default="CLASS",
                        max_length=10,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "월"),
                            (1, "화"),
                            (2, "수"),
                            (3, "목"),
                            (4, "금"),
                            (5, "토"),
                            (6, "일"),
                        ],
                        help_text="요일 (0=월 ~ 6=일)",
                    ),
                ),
                ("start_time", models.TimeField(help_text="시작 시간")),
                (
                    "end_time",
                    models.TimeField(blank=True, help_text="종료 시간", null=True),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="최대 수용 인원", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["section_type", "label"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="반별 차시 (section_mode=true). null이면 반 무관 공통 차시.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="lectures.section",
            ),
        ),
        migrations.CreateModel(
            name="SectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF", "자발적 등록"),
                            ("AUTO", "자동 배정"),
                            ("MANUAL", "수동 배정"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                (
                    "class_section",
                    models.ForeignKey(
                        help_text="수업 정규반",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_assignments",
                        to="lectures.section",
                    ),
                ),
                (
                    "clinic_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="클리닉 정규반 (clinic_mode=regular일 때)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinic_assignments",
                        to="lectures.section",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_assignment",
                        to="enrollment.enrollment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_assignments",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["tenant", "lecture"], name="lectures_se_tenant__ccd53e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("tenant", "lecture", "label", "section_type"),
                name="uniq_section_per_lecture_type",
            ),
        ),
        migrations.AddIndex(
            model_name="sectionassignment",
            index=models.Index(
                fields=["tenant", "class_section"],
                name="lectures_se_tenant__5cfb88_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sectionassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "enrollment"),
                name="uniq_section_assignment_per_enrollment",
            ),
        ),
    ]
