# Generated by Django 5.1.3 on 2026-04-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_section_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionassignment",
            name="class_section",
            field=models.ForeignKey(
                help_text="수업 정규반",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="class_assignments",
                to="lectures.section",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="반별 차시 (section_mode=true). null이면 반 무관 공통 차시.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="lectures.section",
            ),
        ),
    ]
