# Generated by Django 5.1.3 on 2026-04-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0004_fix_section_on_delete"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", False)),
                fields=("lecture", "section", "order"),
                name="uniq_session_order_per_lecture_section",
            ),
        ),
    ]
