# Generated by Django 5.1.3 on 2026-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0005_add_unique_session_order_per_section"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["lecture", "section"], name="lectures_se_lecture_3f1e1b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("section__isnull", True)),
                fields=("lecture", "order"),
                name="uniq_session_order_per_lecture_no_section",
            ),
        ),
    ]
