# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("lectures", "0005_add_lecture_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lecture_time",
            field=models.CharField(
                blank=True, help_text="강의 시간 (예: 토 12:00 ~ 13:00)", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["tenant", "created_at"], name="lectures_le_tenant__ca19dc_idx"
            ),
        ),
    ]
