# Generated by Django 5.1.3 on 2026-06-04 17:33

import re

from django.db import migrations, models


def infer_regular_order(title, display_order):
    match = re.match(r"^\s*(\d+)\s*(?:차시|회차|주차)?", title or "")
    if match:
        return int(match.group(1))
    return int(display_order)


def backfill_session_type_and_regular_order(apps, schema_editor):
    Session = apps.get_model("lectures", "Session")
    used_regular_orders = {}
    sessions = (
        Session.objects
        .only("id", "lecture_id", "section_id", "title", "order")
        .order_by("lecture_id", "section_id", "order", "id")
    )
    for session in sessions.iterator():
        session_type = "SUPPLEMENT" if "보강" in (session.title or "") else "REGULAR"
        regular_order = None
        if session_type == "REGULAR":
            scope_key = (session.lecture_id, session.section_id)
            used = used_regular_orders.setdefault(scope_key, set())
            regular_order = infer_regular_order(session.title, session.order)
            while regular_order in used:
                regular_order += 1
            used.add(regular_order)
        Session.objects.filter(pk=session.pk).update(
            session_type=session_type,
            regular_order=regular_order,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0006_p0_attempt_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="regular_order",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="정규 n차시 번호. 보강 차시는 null이다.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="session_type",
            field=models.CharField(
                choices=[("REGULAR", "정규"), ("SUPPLEMENT", "보강")],
                db_index=True,
                default="REGULAR",
                help_text="차시 유형. 정규 차시와 보강 차시를 제목 추론 없이 구분한다.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="order",
            field=models.PositiveIntegerField(
                help_text="화면 배치 순서. 보강 차시를 포함한다."
            ),
        ),
        migrations.RunPython(
            backfill_session_type_and_regular_order,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("section__isnull", False), ("session_type", "REGULAR")
                ),
                fields=("lecture", "section", "regular_order"),
                name="uniq_regular_session_order_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("section__isnull", True), ("session_type", "REGULAR")
                ),
                fields=("lecture", "regular_order"),
                name="uniq_regular_session_order_no_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("regular_order__isnull", False), ("session_type", "REGULAR")
                    ),
                    models.Q(
                        ("regular_order__isnull", True), ("session_type", "SUPPLEMENT")
                    ),
                    _connector="OR",
                ),
                name="chk_session_regular_order_by_type",
            ),
        ),
    ]
