# Generated by Django 5.1.3 on 2026-02-19 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="폴더 이름", max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="정렬 순서"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="상위 폴더 (null이면 루트 폴더)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="video.videofolder",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="전체공개영상 세션",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_folders",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="video",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="전체공개영상 내 폴더 (일반 차시 영상은 null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="video.videofolder",
            ),
        ),
        migrations.AddIndex(
            model_name="videofolder",
            index=models.Index(
                fields=["session", "parent"], name="video_video_session_645665_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="videofolder",
            constraint=models.UniqueConstraint(
                fields=("session", "parent", "name"), name="unique_video_folder_name"
            ),
        ),
    ]
