# Generated by Django 5.1.3 on 2026-03-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_tenant_messaging_provider_and_more"),
        ("lectures", "0002_lecture_is_system"),
        ("students", "0010_extend_ps_number_max_length"),
        ("video", "0011_video_visibility_tenant_folder_tenant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"ordering": ["order", "title", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="videolike",
            name="video_video_tenant__d89242_idx",
        ),
        migrations.RenameIndex(
            model_name="videofolder",
            new_name="video_video_tenant__00833e_idx",
            old_name="video_videofolder_tenant_parent_idx",
        ),
        migrations.AlterField(
            model_name="video",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="공개 영상 폴더 (일반 차시 영상은 null)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="video.videofolder",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="SET_NULL: Session 삭제 시 soft-delete 보존 (6개월 retention 보장)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="lectures.session",
            ),
        ),
        migrations.AlterField(
            model_name="videocomment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_comments",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="videolike",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_likes",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="videoopsevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="video_ops_events",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="videotranscodejob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_transcode_jobs",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="videolike",
            index=models.Index(
                fields=["tenant", "video"], name="video_video_tenant__d89242_idx"
            ),
        ),
    ]
