# Generated by Django 5.2.16 on 2026-07-28 13:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0050_platformpushoutbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemStudioFontAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "사용 가능"), ("disabled", "사용 중지")],
                        db_index=True,
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("family_name", models.CharField(max_length=160)),
                (
                    "subfamily_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "postscript_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "font_revision",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("r2_key", models.CharField(max_length=512, unique=True)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=100)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("file_format", models.CharField(max_length=8)),
                ("glyph_count", models.PositiveIntegerField(default=0)),
                ("supports_hangul", models.BooleanField(default=False)),
                ("supports_latin", models.BooleanField(default=False)),
                ("fs_type", models.PositiveIntegerField(default=0)),
                (
                    "embedding_permission",
                    models.CharField(default="installable", max_length=32),
                ),
                ("no_subsetting", models.BooleanField(default=False)),
                (
                    "license_basis",
                    models.CharField(
                        choices=[
                            ("purchased", "직접 구매"),
                            ("free", "무료 배포"),
                            ("academy", "학원 보유"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "license_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "license_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("license_note", models.TextField(blank=True, default="")),
                ("rights_confirmed_at", models.DateTimeField()),
                ("redistribution_allowed", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_font_assets",
                        to="core.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_studio_font_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_studio_font_asset",
                "ordering": ["family_name", "subfamily_name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemStudioDocumentStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title_font_key",
                    models.CharField(default="hamchorom-dotum", max_length=40),
                ),
                (
                    "body_font_key",
                    models.CharField(default="hamchorom-batang", max_length=40),
                ),
                (
                    "title_size_pt",
                    models.DecimalField(decimal_places=1, default=20, max_digits=4),
                ),
                (
                    "body_size_pt",
                    models.DecimalField(decimal_places=1, default=10.5, max_digits=4),
                ),
                ("line_spacing_percent", models.PositiveSmallIntegerField(default=155)),
                (
                    "question_spacing_pt",
                    models.DecimalField(decimal_places=1, default=10, max_digits=4),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_document_styles",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_document_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "body_font_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="problem_studio.problemstudiofontasset",
                    ),
                ),
                (
                    "title_font_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="problem_studio.problemstudiofontasset",
                    ),
                ),
            ],
            options={
                "db_table": "problem_studio_document_style",
            },
        ),
        migrations.AddIndex(
            model_name="problemstudiofontasset",
            index=models.Index(
                fields=["tenant", "uploaded_by", "status"],
                name="idx_ps_font_owner_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemstudiofontasset",
            constraint=models.UniqueConstraint(
                fields=("tenant", "uploaded_by", "sha256"),
                name="uq_problem_studio_font_owner_sha",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemstudiodocumentstyle",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uq_problem_studio_style_user"
            ),
        ),
    ]
