# Generated by Django 5.2.16 on 2026-07-28 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_platformpushoutbox"),
        ("problem_studio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemStudioVoiceProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("subject", models.CharField(blank=True, default="", max_length=100)),
                ("style_instructions", models.TextField(blank=True, default="")),
                ("is_default", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "사용 중"), ("archived", "보관")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_voice_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_voice_profiles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "problem_studio_voice_profile",
                "ordering": ["-is_default", "name", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemStudioVoiceSample",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_scope",
                    models.CharField(
                        choices=[
                            ("style", "문체 학습"),
                            ("content_reference", "내용 참고"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("teacher_authored", "선생님 직접 작성"),
                            ("approved_output", "검수 승인 결과"),
                            ("matchup_comment", "매치업 강사 코멘트"),
                            ("publisher_reference", "출판 자료 참고"),
                            ("other_reference", "기타 참고 자료"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("problem_text", models.TextField(blank=True, default="")),
                ("answer", models.TextField(blank=True, default="")),
                ("explanation", models.TextField(blank=True, default="")),
                ("fingerprint", models.CharField(max_length=64)),
                ("rights_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rights_note",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_studio_voice_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="problem_studio.problemstudiovoiceprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_voice_samples",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "problem_studio_voice_sample",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemStudioGenerationReview",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.CharField(max_length=64)),
                ("question_index", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("approved", "승인"),
                            ("edited", "수정 후 승인"),
                            ("rejected", "사용 안 함"),
                        ],
                        max_length=16,
                    ),
                ),
                ("original_payload", models.JSONField(default=dict)),
                ("final_payload", models.JSONField(default=dict)),
                (
                    "feedback_note",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_studio_generation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_studio_generation_reviews",
                        to="core.tenant",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_reviews",
                        to="problem_studio.problemstudiovoiceprofile",
                    ),
                ),
                (
                    "learned_sample",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_review",
                        to="problem_studio.problemstudiovoicesample",
                    ),
                ),
            ],
            options={
                "db_table": "problem_studio_generation_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="problemstudiovoiceprofile",
            index=models.Index(
                fields=["tenant", "owner", "status"], name="idx_ps_voice_owner_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="problemstudiovoiceprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "owner", "name"), name="uq_ps_voice_owner_name"
            ),
        ),
        migrations.AddIndex(
            model_name="problemstudiovoicesample",
            index=models.Index(
                fields=["tenant", "profile", "usage_scope", "is_active"],
                name="idx_ps_voice_sample_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemstudiovoicesample",
            constraint=models.UniqueConstraint(
                fields=("profile", "usage_scope", "fingerprint"),
                name="uq_ps_voice_sample_fingerprint",
            ),
        ),
        migrations.AddIndex(
            model_name="problemstudiogenerationreview",
            index=models.Index(
                fields=["tenant", "reviewed_by", "created_at"],
                name="idx_ps_review_owner_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="problemstudiogenerationreview",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reviewed_by", "job_id", "question_index"),
                name="uq_ps_generation_review_item",
            ),
        ),
    ]
