version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels: [dependencies, security]
    groups:
      aws-sdk:
        patterns: [boto3, botocore]
      test-minor-patch:
        dependency-type: development
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels: [dependencies, security]
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
    labels: [dependencies, security]
    ignore:
      - dependency-name: python
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
