# Generated by Django 5.2.9 on 2026-02-12 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("lectures", "0006_alter_lecture_lecture_time_and_more"),
        ("students", "0009_alter_student_parent_phone_alter_student_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_block_types",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="PostEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="community.blocktype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_entities",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_entities",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_replies",
                        to="students.student",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="community.postentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_replies",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Reply",
                "verbose_name_plural": "Post Replies",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScopeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("COURSE", "강의"), ("SESSION", "차시")], max_length=16
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_nodes",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="community.scopenode",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_nodes",
                        to="lectures.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_nodes",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="community.postentity",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_mappings",
                        to="community.scopenode",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="postentity",
            index=models.Index(
                fields=["tenant", "created_at"], name="community_p_tenant__da765e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postentity",
            index=models.Index(
                fields=["tenant", "block_type"], name="community_p_tenant__0d6a8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scopenode",
            index=models.Index(
                fields=["tenant", "level"], name="community_s_tenant__d27e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scopenode",
            index=models.Index(
                fields=["tenant", "parent"], name="community_s_tenant__c58eec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scopenode",
            unique_together={("tenant", "lecture", "session")},
        ),
        migrations.AddIndex(
            model_name="postmapping",
            index=models.Index(fields=["node"], name="community_p_node_id_547bf8_idx"),
        ),
        migrations.AddConstraint(
            model_name="postmapping",
            constraint=models.UniqueConstraint(
                fields=("post", "node"), name="community_postmapping_post_node_uniq"
            ),
        ),
    ]
