# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        ("core", "0001_initial"),
        ("lectures", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocktype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_block_types",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="postentity",
            name="block_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="community.blocktype",
            ),
        ),
        migrations.AddField(
            model_name="postentity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_entities",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="postentity",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_entities",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="postmapping",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings",
                to="community.postentity",
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_replies",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="community.postentity",
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_replies",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="posttemplate",
            name="block_type",
            field=models.ForeignKey(
                blank=True,
                help_text="기본 유형 (선택)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_templates",
                to="community.blocktype",
            ),
        ),
        migrations.AddField(
            model_name="posttemplate",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_templates",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="scopenode",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_nodes",
                to="lectures.lecture",
            ),
        ),
        migrations.AddField(
            model_name="scopenode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="community.scopenode",
            ),
        ),
        migrations.AddField(
            model_name="scopenode",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_nodes",
                to="lectures.session",
            ),
        ),
        migrations.AddField(
            model_name="scopenode",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scope_nodes",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="postmapping",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_mappings",
                to="community.scopenode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blocktype",
            unique_together={("tenant", "code")},
        ),
        migrations.AddIndex(
            model_name="postentity",
            index=models.Index(
                fields=["tenant", "created_at"], name="community_p_tenant__da765e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postentity",
            index=models.Index(
                fields=["tenant", "block_type"], name="community_p_tenant__0d6a8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="posttemplate",
            index=models.Index(
                fields=["tenant", "order"], name="community_p_tenant__90af91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scopenode",
            index=models.Index(
                fields=["tenant", "level"], name="community_s_tenant__d27e3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scopenode",
            index=models.Index(
                fields=["tenant", "parent"], name="community_s_tenant__c58eec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scopenode",
            unique_together={("tenant", "lecture", "session")},
        ),
        migrations.AddIndex(
            model_name="postmapping",
            index=models.Index(fields=["node"], name="community_p_node_id_547bf8_idx"),
        ),
        migrations.AddConstraint(
            model_name="postmapping",
            constraint=models.UniqueConstraint(
                fields=("post", "node"), name="community_postmapping_post_node_uniq"
            ),
        ),
    ]
