# Generated by Django 5.1.3 on 2026-03-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_initial"),
        ("core", "0013_add_own_messaging_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r2_key", models.CharField(max_length=512, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=128
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="community.postentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_attachments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Attachment",
                "verbose_name_plural": "Post Attachments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "post"], name="community_p_tenant__1a4989_idx"
                    )
                ],
            },
        ),
    ]
