# Generated by Django 5.2.9 on 2026-02-12 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_seed_block_types"),
        ("core", "0014_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="양식 이름 (예: 중간고사 공지)", max_length=128
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="목록 정렬용"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="기본 유형 (선택)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_templates",
                        to="community.blocktype",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "order"],
                        name="community_p_tenant__90af91_idx",
                    )
                ],
            },
        ),
    ]
