# Generated by Django 5.1.3 on 2026-03-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_add_post_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="category_label",
            field=models.CharField(
                blank=True,
                help_text="학생이 선택한 카테고리 (수강 중인 강의명 등)",
                max_length=100,
                null=True,
            ),
        ),
    ]
