# Generated by Django 5.1.3 on 2026-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_add_category_label_to_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="is_urgent",
            field=models.BooleanField(default=False, help_text="긴급 공지 여부"),
        ),
    ]
