# Generated by Django 5.1.3 on 2026-03-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_add_is_urgent_to_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="author_display_name",
            field=models.CharField(
                blank=True,
                help_text="작성자 표시명 (관리자 글: 관리자 이름 저장, 학생 글: created_by에서 파생)",
                max_length=100,
                null=True,
            ),
        ),
    ]
