# Generated by Django 5.1.3 on 2026-03-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_add_post_type_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="postentity",
            new_name="community_p_tenant__69a508_idx",
            old_name="community_p_tenant__pt_idx",
        ),
        migrations.AddField(
            model_name="postentity",
            name="author_role",
            field=models.CharField(
                blank=True,
                default="staff",
                help_text="작성자 역할 (staff/student)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="author_display_name",
            field=models.CharField(
                blank=True,
                help_text="작성자 표시명 (관리자: staff 이름, 학생: created_by에서 파생)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="postreply",
            name="author_role",
            field=models.CharField(
                blank=True,
                default="staff",
                help_text="작성자 역할 (staff/student)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postentity",
            name="author_display_name",
            field=models.CharField(
                blank=True,
                help_text="작성자 표시명 (관리자: staff 이름, 학생: created_by에서 파생)",
                max_length=100,
                null=True,
            ),
        ),
    ]
