# Generated by Django 5.1.3 on 2026-03-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_add_author_role_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postentity",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
