# Generated by Django 5.1.3 on 2026-03-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0009_allow_blank_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="is_pinned",
            field=models.BooleanField(default=False, help_text="상단 고정 여부"),
        ),
        migrations.AddField(
            model_name="postentity",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="예약 게시 시각. null이면 즉시 게시.", null=True
            ),
        ),
        migrations.AddField(
            model_name="postentity",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "임시저장"),
                    ("published", "게시됨"),
                    ("archived", "보관됨"),
                ],
                db_index=True,
                default="published",
                help_text="게시 상태 (draft=임시저장, published=게시됨, archived=보관됨)",
                max_length=20,
            ),
        ),
    ]
