# Generated by Django 5.1.3 on 2026-03-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0010_add_pinned_status_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postentity",
            options={
                "ordering": ["-is_pinned", "-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
