# Generated by Django 5.1.3 on 2026-04-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0011_alter_ordering_pinned_first"),
    ]

    operations = [
        migrations.AddField(
            model_name="postentity",
            name="meta",
            field=models.JSONField(
                blank=True, default=dict, help_text="AI 매치업 결과 등 확장 데이터"
            ),
        ),
    ]
