# Generated by Django 5.1.3 on 2026-05-11 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0015_postlike_postreplylike"),
    ]

    operations = [
        migrations.AddField(
            model_name="postreply",
            name="parent_reply",
            field=models.ForeignKey(
                blank=True,
                help_text="답글 — null이면 최상위 댓글, 값 있으면 해당 댓글의 답글 (2026-05-11 도입).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_replies",
                to="community.postreply",
            ),
        ),
    ]
