# Generated by Django 5.1.3 on 2026-05-11 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0016_postreply_parent_reply"),
        ("core", "0037_landing_testimonial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("post", "글"), ("reply", "댓글")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="PostEntity.id 또는 PostReply.id (target_type에 따라)",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "스팸/광고"),
                            ("offensive", "욕설/혐오"),
                            ("personal_info", "개인정보 노출"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="신고자가 입력한 추가 상세 (선택)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("resolved", "처리됨"),
                            ("dismissed", "기각"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_reports",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "community_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="community_r_tenant__444fe0_idx",
                    ),
                    models.Index(
                        fields=["tenant", "target_type", "target_id"],
                        name="community_r_tenant__1ec75b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_type", "target_id", "reporter"),
                        name="unique_report_per_target_reporter",
                    )
                ],
            },
        ),
    ]
