# Generated by Django 5.1.3 on 2026-05-11 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0017_communityreport"),
        ("core", "0037_landing_testimonial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="communityreport",
            name="unique_report_per_target_reporter",
        ),
        migrations.AddConstraint(
            model_name="communityreport",
            constraint=models.UniqueConstraint(
                fields=("tenant", "target_type", "target_id", "reporter"),
                name="unique_report_per_target_reporter",
            ),
        ),
    ]
