# Generated by Django 5.1.3 on 2026-05-11 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0019_communityuserblock"),
        ("core", "0037_landing_testimonial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("post_reply", "내 글에 댓글"),
                            ("post_like", "내 글에 좋아요"),
                            ("reply_like", "내 댓글에 좋아요"),
                            ("child_reply", "내 댓글에 답글"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_notifications",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "community_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "recipient", "-created_at"],
                        name="community_n_tenant__c3bbc1_idx",
                    ),
                    models.Index(
                        fields=["recipient", "read_at"],
                        name="community_n_recipie_45ee00_idx",
                    ),
                ],
            },
        ),
    ]
