# Generated by Django 5.1.3 on 2026-03-13 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0021_program_billing_mode_program_cancel_at_period_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        default="tosspayments", help_text="PG사", max_length=30
                    ),
                ),
                (
                    "provider_customer_key",
                    models.CharField(
                        blank=True, help_text="PG사 고객 고유 키", max_length=200
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, help_text="결제자 이름", max_length=100
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(
                        blank=True, help_text="결제자 이메일", max_length=254
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True, help_text="결제자 전화번호", max_length=20
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_profile",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 프로필",
                "verbose_name_plural": "결제 프로필",
                "db_table": "billing_profile",
            },
        ),
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(help_text="상호", max_length=200)),
                (
                    "representative_name",
                    models.CharField(help_text="대표자명", max_length=100),
                ),
                (
                    "business_registration_number",
                    models.CharField(
                        help_text="사업자등록번호 (숫자만, 10자리)", max_length=12
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="사업장 주소", max_length=300
                    ),
                ),
                (
                    "business_type",
                    models.CharField(blank=True, help_text="업태", max_length=100),
                ),
                (
                    "business_item",
                    models.CharField(blank=True, help_text="종목", max_length=100),
                ),
                (
                    "tax_invoice_email",
                    models.EmailField(
                        help_text="세금계산서 수신 이메일", max_length=254
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, help_text="담당자 이름", max_length=100
                    ),
                ),
                (
                    "manager_phone",
                    models.CharField(
                        blank=True, help_text="담당자 전화번호", max_length=20
                    ),
                ),
                (
                    "manager_email",
                    models.EmailField(
                        blank=True, help_text="담당자 이메일", max_length=254
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "사업자 정보",
                "verbose_name_plural": "사업자 정보",
                "db_table": "business_profile",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="청구서 번호 (예: INV-2026-03-001)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("plan", models.CharField(help_text="청구 시점 플랜", max_length=20)),
                (
                    "billing_mode",
                    models.CharField(
                        help_text="AUTO_CARD 또는 INVOICE_REQUEST", max_length=20
                    ),
                ),
                (
                    "supply_amount",
                    models.PositiveIntegerField(help_text="공급가액 (부가세 제외)"),
                ),
                (
                    "tax_amount",
                    models.PositiveIntegerField(default=0, help_text="부가세"),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(help_text="합계 (공급가액 + 부가세)"),
                ),
                ("period_start", models.DateField(help_text="구독 기간 시작일")),
                ("period_end", models.DateField(help_text="구독 기간 종료일")),
                ("due_date", models.DateField(help_text="결제 기한")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "예정"),
                            ("PENDING", "결제 대기"),
                            ("PAID", "결제 완료"),
                            ("FAILED", "결제 실패"),
                            ("OVERDUE", "연체"),
                            ("VOID", "무효"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="결제 완료 시각", null=True
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "청구서",
                "verbose_name_plural": "청구서",
                "db_table": "billing_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_key",
                    models.CharField(
                        blank=True, help_text="PG 트랜잭션 키", max_length=200
                    ),
                ),
                (
                    "provider",
                    models.CharField(blank=True, help_text="PG사", max_length=30),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="결제 수단 (card, transfer 등)",
                        max_length=30,
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "처리 중"),
                            ("SUCCESS", "성공"),
                            ("FAILED", "실패"),
                            ("REFUNDED", "환불"),
                            ("PARTIALLY_REFUNDED", "부분 환불"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("card_company", models.CharField(blank=True, max_length=50)),
                ("card_number_masked", models.CharField(blank=True, max_length=20)),
                ("failure_reason", models.TextField(blank=True, help_text="실패 사유")),
                (
                    "raw_response",
                    models.JSONField(default=dict, help_text="PG 원본 응답"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="처리 완료 시각", null=True
                    ),
                ),
                ("refunded_amount", models.PositiveIntegerField(default=0)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="billing.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제 트랜잭션",
                "verbose_name_plural": "결제 트랜잭션",
                "db_table": "billing_payment_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxInvoiceIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_profile_snapshot",
                    models.JSONField(
                        default=dict, help_text="발행 시점 사업자 정보 스냅샷"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUESTED", "미요청"),
                            ("REQUESTED", "발행 요청"),
                            ("READY", "발행 준비"),
                            ("ISSUED", "발행 완료"),
                            ("FAILED", "발행 실패"),
                        ],
                        default="NOT_REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "issue_number",
                    models.CharField(
                        blank=True, help_text="국세청 승인번호", max_length=50
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, help_text="발행 완료 시각", null=True
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True, help_text="발행 요청 시각", null=True
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, help_text="발행 실패 사유"),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_invoice_issue",
                        to="billing.invoice",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_invoice_issues",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "세금계산서 발행",
                "verbose_name_plural": "세금계산서 발행",
                "db_table": "billing_tax_invoice_issue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="tosspayments", max_length=30)),
                (
                    "billing_key",
                    models.CharField(
                        help_text="PG사 빌링키 (암호화 저장 권장)", max_length=200
                    ),
                ),
                (
                    "card_company",
                    models.CharField(
                        blank=True, help_text="카드사 (예: 삼성, 현대)", max_length=50
                    ),
                ),
                (
                    "card_number_masked",
                    models.CharField(
                        blank=True,
                        help_text="마스킹된 카드번호 (예: **** 1234)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_keys",
                        to="core.tenant",
                    ),
                ),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keys",
                        to="billing.billingprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "빌링키",
                "verbose_name_plural": "빌링키",
                "db_table": "billing_key",
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="billing_key_tenant__031b80_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["tenant", "status"], name="billing_inv_tenant__f82d44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="billing_inv_due_dat_e51895_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["tenant", "status"], name="billing_pay_tenant__46a38c_idx"
            ),
        ),
    ]
