# Generated by Django 5.1.3 on 2026-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0025_alter_tenant_messaging_provider_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "period_start", "period_end"),
                name="unique_invoice_per_period",
            ),
        ),
    ]
