# Generated by Django 5.1.3 on 2026-05-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_billingkey_active_partial_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingprofile",
            name="provider_customer_key",
            field=models.CharField(
                blank=True,
                help_text="PG사 고객 고유 키 (예측 불가능한 UUID, 자동 생성)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                help_text="청구서 번호 — 사람이 보는 표시용 (예: INV-2026-03-001)",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_order_id",
            field=models.CharField(
                blank=True,
                help_text="PG 주문 ID (Invoice.provider_order_id와 동일)",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_payment_key",
            field=models.CharField(
                blank=True, help_text="PG사 결제 키 (Toss: paymentKey)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="raw_response",
            field=models.JSONField(
                default=dict,
                help_text="PG 원본 응답 (레거시, response_payload 사용 권장)",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_key",
            field=models.CharField(
                blank=True,
                help_text="PG 트랜잭션 키 (레거시, provider_payment_key 사용 권장)",
                max_length=200,
            ),
        ),
    ]
