# Generated by Django 5.2.16 on 2026-07-27 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_billingkey_provider_key_fingerprint"),
        ("core", "0050_platformpushoutbox"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankTransferNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depositor_name",
                    models.CharField(help_text="입금자명", max_length=100),
                ),
                (
                    "deposited_at",
                    models.DateTimeField(help_text="고객이 입력한 이체 시각"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="확인 대상 청구 금액"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "입금 확인 요청"),
                            ("CONFIRMED", "입금 확인"),
                            ("REJECTED", "확인 반려"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("tax_invoice_requested", models.BooleanField(default=False)),
                (
                    "business_profile_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="세금계산서 요청 시 사업자 정보 스냅샷",
                    ),
                ),
                ("submitted_at", models.DateTimeField(help_text="입금 확인 요청 시각")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("memo", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "계좌이체 입금 확인 요청",
                "verbose_name_plural": "계좌이체 입금 확인 요청",
                "db_table": "billing_bank_transfer_notice",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="taxinvoiceissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("issue_number", ""), _negated=True),
                fields=("issue_number",),
                name="tax_invoice_unique_nonempty_issue_number",
            ),
        ),
        migrations.AddField(
            model_name="banktransfernotice",
            name="invoice",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transfer_notice",
                to="billing.invoice",
            ),
        ),
        migrations.AddField(
            model_name="banktransfernotice",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_bank_transfer_notices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="banktransfernotice",
            index=models.Index(
                fields=["status", "submitted_at"], name="billing_ban_status_94010f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransfernotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "SUBMITTED"), _negated=True),
                    ("reviewed_at__isnull", True),
                    _connector="OR",
                ),
                name="bank_notice_submitted_unreviewed",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransfernotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("CONFIRMED", "REJECTED")), _negated=True),
                    ("reviewed_at__isnull", False),
                    _connector="OR",
                ),
                name="bank_notice_reviewed_has_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransfernotice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REJECTED"), _negated=True),
                    models.Q(("rejection_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="bank_notice_rejected_has_reason",
            ),
        ),
    ]
