# Generated by Django 5.1.3 on 2026-05-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dday",
        ),
    ]
