# PATH: apps/core/migrations/0003_attendance_expense_add_tenant.py
# Generated by Django 5.2.9 on 2026-02-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenantmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="core.tenant",
            ),
        ),
    ]
