# Generated by Django 5.1.3 on 2026-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_tenant_username_per_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="messaging_sender",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
