# Generated by Django 5.1.3 on 2026-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_messaging_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="clinic_idcard_colors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='클리닉 패스카드 배경 그라데이션 색상 3개 (예: ["#ef4444", "#3b82f6", "#22c55e"])',
            ),
        ),
    ]
