# PATH: apps/core/migrations/0006_program.py
# Generated by Django 5.2.9 on 2026-02-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_make_attendance_expense_tenant_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(default="HakwonPlus", max_length=120)),
                (
                    "brand_key",
                    models.CharField(
                        default="hakwonplus",
                        help_text="프론트에서 테마/리소스 로딩 키로 사용 가능 (하드코딩 금지, 데이터 기반)",
                        max_length=80,
                    ),
                ),
                (
                    "login_variant",
                    models.CharField(
                        choices=[
                            ("hakwonplus", "HakwonPlus Admin"),
                            ("limglish", "Limglish Teacher"),
                            ("custom", "Custom"),
                        ],
                        default="hakwonplus",
                        max_length=30,
                    ),
                ),
                ("feature_flags", models.JSONField(blank=True, default=dict)),
                ("ui_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tenant"], name="core_program_tenant__idx"),
                    models.Index(fields=["brand_key"], name="core_program_brand_k_idx"),
                    models.Index(fields=["login_variant"], name="core_program_login_v_idx"),
                ],
            },
        ),
    ]
