# Generated by Django 5.1.3 on 2026-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_clinic_auto_approve_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="student_registration_auto_approve",
            field=models.BooleanField(
                default=False, help_text="True면 학생 가입 신청을 즉시 자동 승인합니다."
            ),
        ),
    ]
