# Generated by Django 5.2.9 on 2026-02-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_program"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="program",
            new_name="core_progra_tenant__551fe8_idx",
            old_name="core_program_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="program",
            new_name="core_progra_brand_k_e09627_idx",
            old_name="core_program_brand_k_idx",
        ),
        migrations.RenameIndex(
            model_name="program",
            new_name="core_progra_login_v_7300df_idx",
            old_name="core_program_login_v_idx",
        ),
    ]
