# Generated by Django 5.2.9 on 2026-02-07 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tenantdomain_and_bootstrap_rows"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="core_tenant_host_573fcb_idx",
            old_name="core_tenantd_host_7f8e3a_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantdomain",
            new_name="core_tenant_tenant__ad1be6_idx",
            old_name="core_tenantd_tenant__c4b2d7_idx",
        ),
    ]
