# Generated by Django 5.1.3 on 2026-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_tenant_headquarters_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="academies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='소속 학원 목록. 예: [{"name": "OO학원", "phone": "02-1234-5678"}]',
            ),
        ),
    ]
