# Generated by Django 5.1.3 on 2026-03-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_tenant_academies"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="messaging_provider",
            field=models.CharField(
                choices=[("solapi", "솔라피(Solapi)"), ("ppurio", "뿌리오(Ppurio)")],
                default="solapi",
                help_text="SMS/알림톡 발송에 사용할 공급자 (solapi 또는 ppurio)",
                max_length=10,
            ),
        ),
    ]
