# Generated by Django 5.1.3 on 2026-03-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_messaging_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="monthly_price",
            field=models.PositiveIntegerField(
                default=300000, help_text="월 요금(원). PLAN_PRICES 기준 자동 설정."
            ),
        ),
    ]
