# Generated by Django 5.2.9 on 2026-02-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tenantdomain_primary_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantdomain",
            name="is_primary",
            field=models.BooleanField(
                default=True,
                help_text="대표 도메인 여부. tenant 당 최대 1개만 True 허용.",
            ),
        ),
    ]
