# Generated by Django 5.1.3 on 2026-03-11 01:55

from django.db import migrations


def set_all_premium(apps, schema_editor):
    Program = apps.get_model("core", "Program")
    Program.objects.all().update(plan="premium", monthly_price=300_000)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_monthly_price_to_program"),
    ]

    operations = [
        migrations.RunPython(set_all_premium, noop),
    ]
