# Generated by Django 5.2.9 on 2026-02-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_program_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="brand_key",
            field=models.CharField(
                default="hakwonplus",
                help_text="프론트 테마/리소스 로딩 키",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="plan",
            field=models.CharField(
                choices=[("lite", "Lite"), ("basic", "Basic"), ("premium", "Premium")],
                default="premium",
                help_text="요금제 (lite/basic/premium)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["plan"], name="core_progra_plan_eaf985_idx"),
        ),
    ]
