# Generated by Django 5.1.3 on 2026-03-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_set_existing_tenants_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="own_ppurio_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 뿌리오 Account ID (직접 연동 시)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="own_ppurio_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 뿌리오 API Key (직접 연동 시)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="own_solapi_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 솔라피 API Key (직접 연동 시)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="own_solapi_api_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 솔라피 API Secret (직접 연동 시)",
                max_length=200,
            ),
        ),
    ]
