# Generated by Django 5.1.3 on 2026-03-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_own_messaging_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="billing_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="결제 관련 이메일 알림 수신",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="subscription_expires_at",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="구독 만료일 (이 날까지 이용 가능)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="subscription_started_at",
            field=models.DateField(blank=True, help_text="구독 시작일", null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "활성"),
                    ("expired", "만료"),
                    ("grace", "유예기간"),
                    ("cancelled", "해지"),
                ],
                db_index=True,
                default="active",
                help_text="구독 상태",
                max_length=20,
            ),
        ),
    ]
