# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_program_brand_key_alter_program_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "date"], name="core_attend_tenant__397c84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "date"], name="core_expens_tenant__5ab126_idx"
            ),
        ),
    ]
