# Generated by Django 5.2.9 on 2026-02-13 02:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="credit_balance",
            field=models.DecimalField(
                decimal_places=0, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="kakao_pfid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="tenant",
            name="messaging_base_price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="messaging_is_active",
            field=models.BooleanField(default=False),
        ),
    ]
