# Generated by Django 5.1.3 on 2026-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_tenant_og_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="billing_mode",
            field=models.CharField(
                choices=[
                    ("AUTO_CARD", "카드 자동결제"),
                    ("INVOICE_REQUEST", "세금계산서 청구"),
                ],
                default="AUTO_CARD",
                help_text="결제 방식: 카드 자동결제 또는 세금계산서 청구",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="cancel_at_period_end",
            field=models.BooleanField(
                default=False, help_text="현재 구독 기간 종료 시 자동 해지"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, help_text="해지 요청 시각", null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="next_billing_at",
            field=models.DateField(blank=True, help_text="다음 결제 예정일", null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="monthly_price",
            field=models.PositiveIntegerField(
                default=198000, help_text="월 요금(원). PLAN_PRICES 기준 자동 설정."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="plan",
            field=models.CharField(
                choices=[("standard", "Standard"), ("pro", "Pro"), ("max", "Max")],
                default="pro",
                help_text="요금제 (standard/pro/max)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="og_image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="카카오톡/SNS 링크 미리보기 이미지 URL (절대 경로 또는 /tenants/... 상대 경로)",
                max_length=500,
            ),
        ),
    ]
