# Generated by Django 5.1.3 on 2026-03-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_program_legal_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_key",
                    models.CharField(
                        choices=[
                            ("minimal_tutor", "Minimal Tutor"),
                            ("premium_dark", "Premium Dark"),
                            ("academic_trust", "Academic Trust"),
                            ("program_promo", "Program Promo"),
                        ],
                        default="minimal_tutor",
                        max_length=30,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("draft_config", models.JSONField(blank=True, default=dict)),
                ("published_config", models.JSONField(blank=True, default=dict)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_page",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_landing_page",
                "indexes": [models.Index(fields=["tenant"], name="idx_landing_tenant")],
            },
        ),
    ]
