# Generated by Django 5.1.3 on 2026-03-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_landing_page"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="landingpage",
            name="idx_landing_tenant",
        ),
    ]
