# Generated by Django 5.1.3 on 2026-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_landing_page_remove_redundant_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="messaging_provider",
            field=models.CharField(
                choices=[
                    ("solapi", "솔라피(Solapi)"),
                    ("ppurio", "비즈뿌리오(BizPpurio)"),
                ],
                default="solapi",
                help_text="SMS/알림톡 발송에 사용할 공급자 (solapi 또는 ppurio=비즈뿌리오)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 비즈뿌리오 계정 ID (직접 연동 시)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="학원 자체 비즈뿌리오 API Key (직접 연동 시)",
                max_length=200,
            ),
        ),
    ]
