# Generated by Django 5.2.12 on 2026-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tenant_messaging_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='messaging_provider',
            field=models.CharField(choices=[('solapi', '솔라피(Solapi)'), ('ppurio', '뿌리오(Ppurio)')], default='solapi', help_text='SMS/알림톡 발송에 사용할 공급자 (solapi 또는 ppurio=뿌리오)', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='own_ppurio_account',
            field=models.CharField(blank=True, default='', help_text='학원 자체 뿌리오 계정 ID (직접 연동 시)', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='own_ppurio_api_key',
            field=models.CharField(blank=True, default='', help_text='학원 자체 뿌리오 API Key (직접 연동 시)', max_length=200),
        ),
    ]
