# Generated by Django 5.1.3 on 2026-04-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_tenant_own_ppurio_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="뿌리오 계정 ID (로그인 아이디, 참고용)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="뿌리오 API Key (인증키 — 뿌리오 아이디 대체 값)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="뿌리오 로그인 비밀번호 (토큰 발급용: Base64(API_KEY:비밀번호))",
                max_length=200,
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_balance__gte", 0)),
                name="credit_balance_non_negative",
            ),
        ),
    ]
