# Generated by Django 5.1.3 on 2026-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_credit_balance_check_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="뿌리오 계정 ID (로그인 아이디 — 토큰 발급 인증에 사용)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="own_ppurio_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="(미사용) 향후 확장용 예비 필드",
                max_length=200,
            ),
        ),
    ]
