# Generated by Django 5.1.3 on 2026-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.PositiveIntegerField(
                default=0,
                help_text="비밀번호 변경 시 +1. JWT claim과 비교하여 기존 토큰 무효화.",
            ),
        ),
    ]
