# Generated by Django 5.1.3 on 2026-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_ops_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeatModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=32)),
                ("instance", models.CharField(default="", max_length=64)),
                ("last_seen_at", models.DateTimeField(db_index=True)),
                ("version", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "db_table": "worker_heartbeat",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "instance"),
                        name="uniq_worker_heartbeat_name_instance",
                    )
                ],
            },
        ),
    ]
