# Generated by Django 5.2.16 on 2026-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_set_ymath_score_summary_column_default'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='tenant',
                    name='messaging_provider',
                    field=models.CharField(choices=[('solapi', '솔라피(Solapi)'), ('ppurio', '뿌리오(Ppurio)')], default='solapi', help_text='레거시 공급자 기록. 제품 실발송에는 사용하지 않음', max_length=10),
                ),
            ],
        ),
    ]
