# Generated by Django 5.2.16 on 2026-09-03 15:51

from django.db import migrations, models


ACADEMY_MIGRATION_PHASE = "contract"
ACADEMY_MIGRATION_REASON = (
    "새 예약 정책 필드는 모든 기존 행에 유효한 DB 기본값을 함께 넣고, 제약은 이후의 잘못된 정책 쓰기만 차단한다."
)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_set_ymath_wrong_completion_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='clinic_booking_interval_minutes',
            field=models.PositiveSmallIntegerField(db_default=60, default=60, help_text='시간 범위 예약의 선택 간격(30분 또는 60분)입니다.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clinic_booking_max_stay_minutes',
            field=models.PositiveIntegerField(db_default=240, default=240, help_text='시간 범위 예약에서 한 학생이 머물 수 있는 최대 분입니다.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='clinic_booking_mode',
            field=models.CharField(choices=[('fixed_slot', '고정 시간대'), ('time_range', '시간 범위')], db_default='fixed_slot', default='fixed_slot', help_text='새 클리닉 세션의 예약 방식 기본값입니다.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('clinic_booking_mode__in', ('fixed_slot', 'time_range'))), name='tenant_clinic_booking_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('clinic_booking_interval_minutes__in', (30, 60))), name='tenant_clinic_booking_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(('clinic_booking_max_stay_minutes__gte', models.F('clinic_booking_interval_minutes'))), name='tenant_clinic_booking_stay_gte_interval'),
        ),
    ]
