# Generated by Django 5.2.16 on 2026-09-26 10:00

import django.db.models.deletion
from django.db import migrations, models


ACADEMY_MIGRATION_PHASE = "expand"
ACADEMY_MIGRATION_REASON = (
    "Add an isolated candidate QA action ledger without tenant FKs or destructive cleanup."
)


def protect_receipts(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        CREATE FUNCTION candidate_qa_immutable_row() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'candidate QA evidence is immutable';
        END;
        $$;
    """)
    for table, events in (
        ("candidate_qa_run", "DELETE"),
        ("candidate_qa_action", "UPDATE OR DELETE"),
        ("candidate_qa_receipt", "UPDATE OR DELETE"),
    ):
        schema_editor.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE {events} ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION candidate_qa_immutable_row();"
        )


def unprotect_receipts(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for table in ("candidate_qa_run", "candidate_qa_action", "candidate_qa_receipt"):
        schema_editor.execute(f"DROP TRIGGER {table}_immutable ON {table};")
    schema_editor.execute("DROP FUNCTION candidate_qa_immutable_row();")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_tenant_clinic_use_daily_random_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQaRun',
            fields=[
                ('lease_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('root_sha256', models.CharField(max_length=64)),
                ('binding_sha256', models.CharField(max_length=64)),
                ('owner_task', models.CharField(max_length=36)),
                ('source_sha', models.CharField(max_length=40)),
                ('tenant_ids', models.JSONField()),
                ('domains', models.JSONField()),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('receipt_count', models.PositiveIntegerField(default=0)),
                ('fenced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_qa_run',
            },
        ),
        migrations.CreateModel(
            name='CandidateQaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=32)),
                ('domain', models.CharField(max_length=16)),
                ('action_type', models.CharField(max_length=48)),
                ('tenant_id', models.PositiveBigIntegerField()),
                ('origin_kind', models.CharField(max_length=16)),
                ('operation_revision', models.PositiveBigIntegerField()),
                ('args_sha256', models.CharField(max_length=64)),
                ('intent_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.candidateqarun')),
            ],
            options={
                'db_table': 'candidate_qa_action',
            },
        ),
        migrations.CreateModel(
            name='CandidateQaReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=32)),
                ('kind', models.CharField(choices=[('locator', 'Locator'), ('outcome', 'Outcome'), ('cleanup', 'Cleanup evidence')], max_length=16)),
                ('locator_kind', models.CharField(blank=True, default='', max_length=24)),
                ('locator_type', models.CharField(blank=True, default='', max_length=80)),
                ('locator_ref', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Confirmed success'), ('failure', 'Confirmed failure'), ('unknown', 'Uncertain result')], default='', max_length=16)),
                ('proof_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('event_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.candidateqaaction')),
            ],
            options={
                'db_table': 'candidate_qa_receipt',
                'indexes': [models.Index(fields=['action', 'id'], name='candidate_qa_receipt_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('action', 'event_id'), name='uniq_candidate_qa_receipt')],
            },
        ),
        migrations.AddIndex(
            model_name='candidateqaaction',
            index=models.Index(fields=['run', 'domain', 'tenant_id'], name='candidate_qa_action_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateqaaction',
            constraint=models.UniqueConstraint(fields=('run', 'action_id'), name='uniq_candidate_qa_action'),
        ),
        migrations.RunPython(protect_receipts, unprotect_receipts),
    ]
