# Generated by Django 5.2.9 on 2025-12-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
        ("enrollment", "0001_initial"),
        ("lectures", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardpost",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="boardpost",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_posts",
                to="lectures.lecture",
            ),
        ),
        migrations.AddField(
            model_name="boardattachment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="boards.boardpost",
            ),
        ),
        migrations.AddField(
            model_name="boardreadstatus",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enrollment.enrollment"
            ),
        ),
        migrations.AddField(
            model_name="boardreadstatus",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_status",
                to="boards.boardpost",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardreadstatus",
            unique_together={("post", "enrollment")},
        ),
    ]
