# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("default", "기본"),
                            ("lecture", "강의"),
                            ("clinic", "클리닉"),
                        ],
                        db_index=True,
                        default="default",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="템플릿 이름", max_length=120)),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", help_text="제목(선택)", max_length=200
                    ),
                ),
                ("body", models.TextField(help_text="본문")),
                (
                    "solapi_template_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "solapi_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "미신청"),
                            ("PENDING", "검수 대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message templates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "amount_deducted",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "recipient_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "template_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification log",
                "verbose_name_plural": "Notification logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
