# Generated by Django 5.2.9

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoSendConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("student_signup", "가입 완료"),
                            ("clinic_reminder", "클리닉 알림"),
                            ("clinic_reservation_created", "클리닉 예약 생성"),
                            ("clinic_reservation_changed", "클리닉 예약 변경"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "message_mode",
                    models.CharField(
                        choices=[
                            ("sms", "SMS만"),
                            ("alimtalk", "알림톡만"),
                            ("both", "알림톡→SMS폴백"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_send_configs",
                        to="messaging.messagetemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_send_configs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto-send config",
                "verbose_name_plural": "Auto-send configs",
                "unique_together": {("tenant", "trigger")},
            },
        ),
    ]
