# Generated by Django 5.1.3 on 2026-03-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_autosendconfig_minutes_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="message_body",
            field=models.TextField(
                blank=True, default="", help_text="실제 발송된 메시지 본문"
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="message_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sms", "SMS"),
                    ("alimtalk", "알림톡"),
                    ("both", "알림톡→SMS"),
                ],
                default="",
                help_text="발송 방식",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="autosendconfig",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("student_signup", "가입 완료"),
                    ("registration_approved_student", "가입 승인(학생)"),
                    ("registration_approved_parent", "가입 승인(학부모)"),
                    ("class_enrollment_complete", "반 등록 완료"),
                    ("enrollment_expiring_soon", "등록 만료 예정"),
                    ("withdrawal_complete", "퇴원 처리 완료"),
                    ("lecture_session_reminder", "수업 시작 N분 전"),
                    ("check_in_complete", "입실 완료"),
                    ("absent_occurred", "결석 발생"),
                    ("exam_scheduled_days_before", "시험 예정 N일 전"),
                    ("exam_start_minutes_before", "시험 시작 N분 전"),
                    ("exam_not_taken", "시험 미응시"),
                    ("exam_score_published", "성적 공개"),
                    ("retake_assigned", "재시험 대상 지정"),
                    ("assignment_registered", "과제 등록"),
                    ("assignment_due_hours_before", "과제 마감 N시간 전"),
                    ("assignment_not_submitted", "과제 미제출"),
                    ("monthly_report_generated", "월간 성적 리포트 발송"),
                    ("clinic_reminder", "클리닉 시작 N분 전"),
                    ("clinic_reservation_created", "클리닉 예약 완료"),
                    ("clinic_reservation_changed", "클리닉 예약 변경"),
                    ("counseling_reservation_created", "상담 예약 완료"),
                    ("payment_complete", "결제 완료"),
                    ("payment_due_days_before", "납부 예정일 N일 전"),
                    ("urgent_notice", "긴급 공지"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("default", "기본"),
                    ("signup", "가입/등록"),
                    ("attendance", "출결"),
                    ("lecture", "강의"),
                    ("exam", "시험"),
                    ("assignment", "과제"),
                    ("grades", "성적"),
                    ("clinic", "클리닉"),
                    ("payment", "결제"),
                    ("notice", "운영공지"),
                ],
                db_index=True,
                default="default",
                max_length=20,
            ),
        ),
    ]
