# Generated by Django 5.1.3 on 2026-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_is_system_is_user_default_to_template"),
        ("messaging", "0012_add_both_message_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="시스템 기본 양식 여부. True이면 사용자 수정/삭제 불가.",
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="is_user_default",
            field=models.BooleanField(
                default=False,
                help_text="사용자가 해당 카테고리에서 기본 양식으로 지정한 템플릿. tenant+category당 1개만.",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_user_default", True)),
                fields=("tenant", "category"),
                name="uniq_user_default_per_tenant_category",
            ),
        ),
    ]
