# Generated by Django 5.1.3 on 2026-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0014_backfill_is_system_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("default", "기본"),
                    ("signup", "가입/등록"),
                    ("attendance", "출결"),
                    ("lecture", "강의"),
                    ("exam", "시험"),
                    ("assignment", "과제"),
                    ("grades", "성적"),
                    ("clinic", "클리닉"),
                    ("payment", "결제"),
                    ("notice", "운영공지"),
                    ("community", "커뮤니티"),
                    ("staff", "직원"),
                ],
                db_index=True,
                default="default",
                max_length=20,
            ),
        ),
    ]
