# Generated by Django 5.1.3 on 2026-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0017_clear_old_solapi_template_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autosendconfig",
            name="message_mode",
            field=models.CharField(
                choices=[("sms", "SMS만"), ("alimtalk", "알림톡만"), ("both", "둘 다")],
                default="alimtalk",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="autosendconfig",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("student_signup", "가입 완료(레거시·미사용)"),
                    ("registration_approved_student", "가입 안내(학생)"),
                    ("registration_approved_parent", "가입 안내(학부모)"),
                    ("class_enrollment_complete", "반 등록 완료"),
                    ("enrollment_expiring_soon", "등록 만료 예정"),
                    ("withdrawal_complete", "퇴원 처리 완료"),
                    ("lecture_session_reminder", "수업 시작 N분 전"),
                    ("check_in_complete", "입실 완료(일반 강의)"),
                    ("absent_occurred", "결석 발생(일반 강의)"),
                    ("exam_scheduled_days_before", "시험 예정 N일 전"),
                    ("exam_start_minutes_before", "시험 시작 N분 전"),
                    ("exam_not_taken", "시험 미응시"),
                    ("exam_score_published", "성적 공개"),
                    ("retake_assigned", "재시험 대상 지정"),
                    ("assignment_registered", "과제 등록"),
                    ("assignment_due_hours_before", "과제 마감 N시간 전"),
                    ("assignment_not_submitted", "과제 미제출"),
                    ("monthly_report_generated", "월간 성적 리포트 발송"),
                    ("clinic_reminder", "클리닉 시작 N분 전"),
                    ("clinic_reservation_created", "클리닉 예약 완료"),
                    ("clinic_reservation_changed", "클리닉 예약 변경"),
                    ("clinic_cancelled", "클리닉 예약 취소"),
                    ("clinic_check_in", "클리닉 입실"),
                    ("clinic_check_out", "클리닉 퇴실(완료)"),
                    ("clinic_absent", "클리닉 결석"),
                    ("clinic_self_study_completed", "자율학습 완료"),
                    ("clinic_result_notification", "클리닉 대상 해소(완료)"),
                    ("counseling_reservation_created", "상담 예약 완료"),
                    ("payment_complete", "결제 완료"),
                    ("payment_due_days_before", "납부 예정일 N일 전"),
                    ("video_encoding_complete", "영상 인코딩 완료"),
                    ("password_find_otp", "비밀번호 찾기 인증번호"),
                    ("password_reset_student", "비밀번호 재설정(학생)"),
                    ("password_reset_parent", "비밀번호 재설정(학부모)"),
                ],
                db_index=True,
                max_length=60,
            ),
        ),
    ]
