# Generated by Django 5.2.16 on 2026-08-19 17:29

from django.contrib.postgres.operations import NotInTransactionMixin
from django.db import migrations, models


class AddIndexConcurrentlyOnPostgres(NotInTransactionMixin, migrations.AddIndex):
    """Keep SQLite test migrations portable while avoiding PostgreSQL write locks."""

    atomic = False

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return
        if schema_editor.connection.vendor == "postgresql":
            self._ensure_not_in_transaction(schema_editor)
            schema_editor.add_index(model, self.index, concurrently=True)
            return
        schema_editor.add_index(model, self.index)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return
        if schema_editor.connection.vendor == "postgresql":
            self._ensure_not_in_transaction(schema_editor)
            schema_editor.remove_index(model, self.index, concurrently=True)
            return
        schema_editor.remove_index(model, self.index)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0055_set_ymath_score_summary_column_default"),
        ("messaging", "0035_finalize_messaging_delivery_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="origin_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Producer job/batch/domain identifier without recipient PII",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="origin_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Durable producer kind such as excel_import or manual_send",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="recipient_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HMAC fingerprint of the normalized recipient; never the raw phone number",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="origin_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="원천 job/batch/domain 식별자",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="origin_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="발송 원천 종류(excel_import, manual_send 등)",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="schedulednotification",
            name="recipient_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="정규화 수신번호의 HMAC 지문(원문 번호 저장 금지)",
                max_length=64,
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="notificationlog",
            index=models.Index(
                fields=["recipient_fingerprint", "sent_at"],
                name="idx_notif_recipient_time",
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="notificationlog",
            index=models.Index(
                fields=["origin_id", "sent_at"], name="idx_notif_origin_time"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="schedulednotification",
            index=models.Index(
                fields=["recipient_fingerprint", "created_at"],
                name="idx_sched_recipient_time",
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="schedulednotification",
            index=models.Index(
                fields=["origin_id", "created_at"], name="idx_sched_origin_time"
            ),
        ),
        AddIndexConcurrentlyOnPostgres(
            model_name="schedulednotification",
            index=models.Index(
                fields=["last_attempt_at"], name="idx_sched_last_attempt"
            ),
        ),
    ]
