# Generated by Django 5.2.16 on 2026-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0036_notificationlog_origin_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='schedulednotification',
                    name='payload',
                    field=models.JSONField(help_text='enqueue_alimtalk kwargs (to, text, message_mode, template_id, etc.)'),
                ),
            ],
        ),
    ]
