# Generated by Django 5.2.16 on 2026-09-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_tenant_clinic_booking_interval_minutes_and_more'),
        ('messaging', '0040_provision_clinic_checkout_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlimtalkChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending_templates', '템플릿 검수 중'), ('active', '사용 가능'), ('suspended', '사용 중지')], db_index=True, default='pending_templates', max_length=24)),
                ('verified_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField()),
                ('test_template_id', models.CharField(blank=True, default='', max_length=100)),
                ('test_template_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('last_test_status', models.CharField(blank=True, choices=[('sent', '발송 접수'), ('failed', '발송 실패'), ('ambiguous', '결과 확인 필요')], default='', max_length=16)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alimtalk_channel_binding', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant_id'],
            },
        ),
        migrations.CreateModel(
            name='AlimtalkTemplateBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_template_id', models.CharField(max_length=100)),
                ('channel_template_id', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('channel_fingerprint', models.CharField(max_length=64)),
                ('last_synced_at', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_bindings', to='messaging.alimtalkchannelbinding')),
            ],
            options={
                'ordering': ['source_template_id'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'source_template_id'), name='uniq_alimtalk_source_template_per_channel')],
            },
        ),
    ]
