# Generated by Django 5.2.17 on 2026-10-02 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_account_notice_credentials"),
        ("messaging", "0042_defaulttemplatesuppression"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualSendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.UUIDField()),
                (
                    "recipient_scope",
                    models.CharField(
                        choices=[("student", "학생"), ("parent", "학부모")],
                        max_length=20,
                    ),
                ),
                ("actor_user_id", models.PositiveBigIntegerField()),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("outbox_ids", models.JSONField(default=list)),
                ("skipped_no_phone", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_send_requests",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "request_id", "recipient_scope"),
                        name="uniq_manual_request_scope",
                    )
                ],
            },
        ),
    ]
