# Generated by Django 5.2.9 on 2026-02-13 02:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0015_add_tenant_messaging_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("success", models.BooleanField(default=False)),
                (
                    "amount_deducted",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "recipient_summary",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "template_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification log",
                "verbose_name_plural": "Notification logs",
                "ordering": ["-sent_at"],
            },
        ),
    ]
