# Generated by Django 5.2.9 on 2026-02-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_tenant_messaging_fields"),
        ("messaging", "0001_notification_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="템플릿 이름", max_length=120)),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", help_text="제목(선택)", max_length=200
                    ),
                ),
                ("body", models.TextField(help_text="본문")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message templates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
