# Generated by Django 5.2.9 on 2026-02-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_message_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("default", "기본"),
                    ("lecture", "강의"),
                    ("clinic", "클리닉"),
                ],
                db_index=True,
                default="default",
                max_length=20,
            ),
        ),
    ]
