# Generated by Django 5.1.3 on 2026-03-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_program_legal_fields"),
        ("messaging", "0008_add_clinic_self_study_completed_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="batch_id",
            field=models.UUIDField(
                blank=True, db_index=True, help_text="수동 발송 배치 ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification_type",
            field=models.CharField(
                blank=True, default="", help_text="check_in, absent 등", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="sender_staff_id",
            field=models.IntegerField(
                blank=True, help_text="발송 요청 Staff ID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="business_idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of business dedup key (tenant+channel+event+target+recipient). Empty for legacy.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("processing", "처리중"),
                    ("sent", "발송완료"),
                    ("failed", "실패"),
                ],
                default="sent",
                help_text="발송 상태. processing=선점됨, sent=발송완료, failed=실패",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreviewToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(db_index=True, unique=True)),
                (
                    "notification_type",
                    models.CharField(
                        help_text="check_in | absent | clinic_reminder 등",
                        max_length=30,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(help_text="attendance | clinic", max_length=20),
                ),
                ("session_id", models.IntegerField()),
                ("send_to", models.CharField(default="parent", max_length=20)),
                (
                    "payload",
                    models.JSONField(help_text="직렬화된 수신자 + 메시지 데이터"),
                ),
                (
                    "created_by_id",
                    models.IntegerField(blank=True, help_text="Staff ID", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="소비 시각 (non-null=사용됨)", null=True
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("batch_id", models.UUIDField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preview_tokens",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification preview token",
                "verbose_name_plural": "Notification preview tokens",
            },
        ),
    ]
