# Generated by Django 5.1.3 on 2026-04-03 09:54

from django.db import migrations


def backfill_is_system(apps, schema_editor):
    """기존 [학원플러스] 접두어 템플릿에 is_system=True 설정"""
    MessageTemplate = apps.get_model("messaging", "MessageTemplate")
    updated = MessageTemplate.objects.filter(
        name__startswith="[학원플러스]",
        is_system=False,
    ).update(is_system=True)
    if updated:
        print(f"\n  → backfill: {updated}개 시스템 템플릿에 is_system=True 설정")


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0013_add_is_system_is_user_default_to_template"),
    ]

    operations = [
        migrations.RunPython(backfill_is_system, migrations.RunPython.noop),
    ]
