# Generated by Django 5.1.3 on 2026-04-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0020_autosend_delay_and_scheduled_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="autosendconfig",
            name="show_actual_time",
            field=models.BooleanField(default=False),
        ),
    ]
