# Generated by Django 5.2.16 on 2026-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryfile",
            name="student_ps",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="inventoryfolder",
            name="student_ps",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=50
            ),
        ),
    ]
