# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIRuntimeConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "db_table": "ai_runtime_config",
            },
        ),
        migrations.CreateModel(
            name="TenantConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("has_premium_subscription", models.BooleanField(default=False)),
                ("allow_gpu_fallback", models.BooleanField(default=False)),
                ("gpu_fallback_threshold", models.FloatField(default=0.5)),
            ],
            options={
                "db_table": "ai_tenant_config",
            },
        ),
        migrations.CreateModel(
            name="AIJobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_id", models.CharField(max_length=64, unique=True)),
                ("job_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("VALIDATING", "VALIDATING"),
                            ("RUNNING", "RUNNING"),
                            ("DONE", "DONE"),
                            ("FAILED", "FAILED"),
                            ("REJECTED_BAD_INPUT", "REJECTED_BAD_INPUT"),
                            ("FALLBACK_TO_GPU", "FALLBACK_TO_GPU"),
                            ("RETRYING", "RETRYING"),
                            ("REVIEW_REQUIRED", "REVIEW_REQUIRED"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("tenant_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "source_domain",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("source_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("lite", "Lite"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                        ],
                        db_index=True,
                        default="basic",
                        help_text="Tier determines queue routing and processing capabilities",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("locked_by", models.CharField(blank=True, max_length=128, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="tenant_id:exam_id:student_id:job_type:file_hash, 중복 요청 방지",
                        max_length=256,
                        null=True,
                        unique=True,
                    ),
                ),
                ("force_rerun", models.BooleanField(default=False)),
                ("rerun_reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ai_job",
                "indexes": [
                    models.Index(
                        fields=["status", "next_run_at"],
                        name="ai_job_status_next_run_idx",
                    ),
                    models.Index(fields=["lease_expires_at"], name="ai_job_lease_idx"),
                    models.Index(
                        fields=["source_domain", "source_id"], name="ai_job_source_idx"
                    ),
                    models.Index(
                        fields=["tier", "status", "next_run_at"],
                        name="ai_job_tier_stat_next_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="ai_domain.aijobmodel",
                    ),
                ),
            ],
            options={
                "db_table": "ai_result",
            },
        ),
    ]
