# Generated by Django 5.1.3 on 2026-04-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_domain", "0001_initial"),
        ("core", "0017_rename_plans_standard_pro_max"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        db_index=True,
                        help_text="matchup / ocr / embedding / problem_generation / schema_infer",
                        max_length=32,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="일일 한도 추적용. 0이면 월간 집계 row."
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usages",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage",
                "indexes": [
                    models.Index(
                        fields=["tenant", "kind", "year", "month"],
                        name="ai_usage_tenant__73fb0b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "kind", "year", "month", "day"),
                        name="uniq_ai_usage_per_period",
                    )
                ],
            },
        ),
    ]
