# Generated by Django 5.2.x on 2026-01-31
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ai_domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aijobmodel",
            name="tenant_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="source_domain",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="source_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="max_attempts",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="locked_by",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="last_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="next_run_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="aijobmodel",
            index=models.Index(fields=["status", "next_run_at"], name="ai_job_status_next_run_idx"),
        ),
        migrations.AddIndex(
            model_name="aijobmodel",
            index=models.Index(fields=["lease_expires_at"], name="ai_job_lease_idx"),
        ),
        migrations.AddIndex(
            model_name="aijobmodel",
            index=models.Index(fields=["source_domain", "source_id"], name="ai_job_source_idx"),
        ),
    ]
