# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_domain", "0002_aiusagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="aijobmodel",
            name="completed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="aijobmodel",
            name="started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
