# Generated by Django 5.2.9 on 2026-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_domain", "0003_alter_aijobmodel_status_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="aijobmodel",
            name="ai_job_status_ba4967_idx",
        ),
        migrations.RemoveIndex(
            model_name="aijobmodel",
            name="ai_job_locked__f6f4a2_idx",
        ),
        migrations.AlterField(
            model_name="aijobmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("RUNNING", "RUNNING"),
                    ("DONE", "DONE"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
