# Generated by Django 5.2.9 on 2026-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_domain", "0004_remove_aijobmodel_ai_job_status_ba4967_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijobmodel",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="aijobmodel",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
