# Generated by Django 5.2.9 on 2026-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "출석"),
                            ("LATE", "지각"),
                            ("ONLINE", "온라인"),
                            ("SUPPLEMENT", "보강"),
                            ("EARLY_LEAVE", "조퇴"),
                            ("ABSENT", "결석"),
                            ("RUNAWAY", "출튀"),
                            ("MATERIAL", "자료"),
                            ("INACTIVE", "부재"),
                            ("SECESSION", "탈퇴"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
