# Generated by Django 5.2.9 on 2026-01-06 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("enrollment", "0001_initial"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="enrollment.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="lectures.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "session"), name="unique_attendance_per_session"
            ),
        ),
    ]
