# Generated by Django 5.1.3 on 2026-04-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("lectures", "0003_section_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attended_section",
            field=models.ForeignKey(
                blank=True,
                help_text="실제 출석한 반 (section_mode=true). null이면 반 무관.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="lectures.section",
            ),
        ),
    ]
