# Generated by Django 5.2.9 on 2026-02-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_add_tenant"),
        ("core", "0003_attendance_expense_add_tenant"),
        ("enrollment", "0002_add_tenant"),
        ("lectures", "0002_remove_session_exam"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attendance",
            name="unique_attendance_per_session",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_attendances",
                to="core.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("tenant", "enrollment", "session"),
                name="unique_attendance_per_tenant_session",
            ),
        ),
    ]
