# Generated by Django 5.1.3 on 2026-07-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_section_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNSET", "미입력"),
                    ("PRESENT", "출석"),
                    ("LATE", "지각"),
                    ("ONLINE", "온라인"),
                    ("SUPPLEMENT", "보강"),
                    ("EARLY_LEAVE", "조퇴"),
                    ("ABSENT", "결석"),
                    ("RUNAWAY", "출튀"),
                    ("MATERIAL", "자료"),
                    ("INACTIVE", "부재"),
                    ("SECESSION", "탈퇴"),
                ],
                default="UNSET",
                max_length=20,
            ),
        ),
    ]
