# Generated by Django 5.2.16 on 2026-08-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_attendance_unset_default"),
        ("core", "0052_user_first_login_guide_completed_at"),
        ("enrollment", "0001_initial"),
        ("lectures", "0007_session_regular_order_session_session_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="planned_arrival_date",
            field=models.DateField(
                blank=True,
                help_text="보강 학생의 예정 등원 날짜. 값이 있을 때 등원 예정으로 집계한다.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="planned_arrival_time",
            field=models.TimeField(
                blank=True,
                help_text="보강 학생의 예정 등원 시간. 날짜만 정해진 경우 비워둘 수 있다.",
                null=True,
            ),
        ),
    ]
