# Generated by Django 5.2.9 on 2026-02-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_backfill_attendance_tenant"),
        ("core", "0014_alter_user_phone_and_more"),
        ("enrollment", "0004_alter_enrollment_tenant_and_more"),
        ("lectures", "0006_alter_lecture_lecture_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_attendances",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["tenant", "recorded_at"], name="attendance__tenant__65bff1_idx"
            ),
        ),
    ]
