# Generated by Django 5.2.9 on 2025-12-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="external_url",
        ),
        migrations.RemoveField(
            model_name="video",
            name="file",
        ),
        migrations.RemoveField(
            model_name="video",
            name="youtube_id",
        ),
        migrations.AddField(
            model_name="video",
            name="hls_path",
            field=models.CharField(
                blank=True,
                help_text="HLS master playlist path (relative to CDN root)",
                max_length=500,
            ),
        ),
    ]
