# Generated by Django 5.2.9 on 2026-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_attendance_expense_add_tenant"),
        ("enrollment", "0002_add_tenant"),
        ("lectures", "0002_remove_session_exam"),
        ("students", "0002_add_tenant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="unique_enrollment_per_lecture",
        ),
        migrations.AlterUniqueTogether(
            name="sessionenrollment",
            unique_together={("tenant", "session", "enrollment")},
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "student", "lecture"),
                name="unique_enrollment_per_tenant_lecture",
            ),
        ),
    ]
