# Generated by Django 5.2.9 on 2026-02-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("enrollment", "0003_remove_enrollment_unique_enrollment_per_lecture_and_more"),
        ("lectures", "0006_alter_lecture_lecture_time_and_more"),
        ("students", "0009_alter_student_parent_phone_alter_student_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="sessionenrollment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session_enrollments",
                to="core.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["tenant", "created_at"], name="enrollment__tenant__5d24f1_idx"
            ),
        ),
    ]
