# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "phone",
                    models.CharField(
                        help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="학부모 로그인 계정 (ID = 학부모 전화번호)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="parents_par_tenant__442d73_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "phone"), name="uniq_parent_phone_per_tenant"
                    )
                ],
            },
        ),
    ]
