# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("parents", "0005_add_parent_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="phone",
            field=models.CharField(
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["tenant", "created_at"], name="parents_par_tenant__442d73_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parent",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone"), name="uniq_parent_phone_per_tenant"
            ),
        ),
    ]
