# Generated by Django 5.1.3 on 2026-03-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0005_staff_profile_photo"),
        ("students", "0005_add_registration_request_username"),
        ("video", "0007_videoopsevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True)),
                ("content", models.TextField(max_length=2000)),
                ("is_edited", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.PositiveIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name="videoopsevent",
            new_name="video_video_type_203b08_idx",
            old_name="video_videoo_type_0a1b0d_idx",
        ),
        migrations.RenameIndex(
            model_name="videotranscodejob",
            new_name="video_video_state_8aa346_idx",
            old_name="video_transcodejob_state_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="videotranscodejob",
            new_name="video_video_tenant__af7098_idx",
            old_name="video_transcodejob_tenant_state_idx",
        ),
        migrations.AddField(
            model_name="video",
            name="comment_count",
            field=models.PositiveIntegerField(default=0, help_text="댓글 수"),
        ),
        migrations.AddField(
            model_name="video",
            name="like_count",
            field=models.PositiveIntegerField(default=0, help_text="좋아요 수"),
        ),
        migrations.AddField(
            model_name="video",
            name="view_count",
            field=models.PositiveIntegerField(default=0, help_text="재생 시작 횟수"),
        ),
        migrations.AlterField(
            model_name="videoopsevent",
            name="severity",
            field=models.CharField(
                choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")],
                db_index=True,
                default="WARNING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="videoopsevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("JOB_DEAD", "Job DEAD"),
                    ("BATCH_DESYNC", "Batch-DB 불일치"),
                    ("UPLOAD_INTEGRITY_FAIL", "R2 업로드 무결성 실패"),
                    ("ORPHAN_CANCELLED", "Orphan Batch job 취소"),
                    ("TENANT_LIMIT_EXCEEDED", "테넌트 동시 실행 한도 초과"),
                    (
                        "VIDEO_DELETE_TERMINATE_REQUESTED",
                        "영상 삭제 시 Batch 종료 요청",
                    ),
                    ("VIDEO_DELETE_TERMINATE_FAILED", "영상 삭제 시 Batch 종료 실패"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="videotranscodejob",
            name="state",
            field=models.CharField(
                choices=[
                    ("QUEUED", "대기"),
                    ("RUNNING", "실행중"),
                    ("SUCCEEDED", "완료"),
                    ("FAILED", "실패"),
                    ("RETRY_WAIT", "재시도대기"),
                    ("DEAD", "격리"),
                    ("CANCELLED", "취소됨"),
                ],
                db_index=True,
                default="QUEUED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videocomment",
            name="author_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_comments",
                to="staffs.staff",
            ),
        ),
        migrations.AddField(
            model_name="videocomment",
            name="author_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_comments",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="videocomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="video.videocomment",
            ),
        ),
        migrations.AddField(
            model_name="videocomment",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="video.video",
            ),
        ),
        migrations.AddField(
            model_name="videolike",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_likes",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="videolike",
            name="video",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="video.video",
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["video", "created_at"], name="video_video_video_i_422052_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["tenant_id", "video"], name="video_video_tenant__34594c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["parent"], name="video_video_parent__5c78d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videolike",
            index=models.Index(
                fields=["tenant_id", "video"], name="video_video_tenant__d89242_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="videolike",
            constraint=models.UniqueConstraint(
                fields=("video", "student"), name="unique_video_like"
            ),
        ),
    ]
