# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0008_videocomment_videolike_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Soft-delete timestamp. Non-null means the video is logically deleted.",
                null=True,
            ),
        ),
    ]
