# Generated by Django 5.1.3 on 2026-04-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0006_workrecord_auto_calc_work_hours"),
        ("video", "0013_video_tenant_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="영상을 업로드한 스태프. 인코딩 완료 알림 발송 대상.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_videos",
                to="staffs.staff",
            ),
        ),
    ]
