# Generated by Django 5.1.3 on 2026-05-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0015_video_thumbnail_r2_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="thumbnail_r2_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="R2 key of generated thumbnail. Worker invariant: 항상 채워짐.",
                max_length=500,
            ),
        ),
    ]
