# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0016_alter_video_thumbnail_r2_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="videotranscodejob",
            name="last_counted_failure_aws_batch_job_id",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
