# Generated by Django 5.2.16 on 2026-08-27 08:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_tenant_controls_messaging_activation'),
        ('enrollment', '0002_student_deletion_status_snapshot'),
        ('students', '0019_registration_request_student_history'),
        ('video', '0020_videoprogress_forward_skip_seconds_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveVideoEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_mode', models.CharField(choices=[('FREE_REVIEW', '복습'), ('PROCTORED_CLASS', '온라인 수업 대체')], max_length=20)),
                ('source', models.CharField(choices=[('STAFF_AUTHORIZATION', '교직원 명시 승인')], max_length=32)),
                ('source_reference', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('granted_by_reference', models.CharField(max_length=128)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_reference', models.CharField(blank=True, default='', max_length=128)),
                ('revoke_reason', models.TextField(blank=True, default='')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_video_entitlements', to='enrollment.enrollment')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_inactive_video_entitlements', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_inactive_video_entitlements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_video_entitlements', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_video_entitlements', to='core.tenant')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_enrollment_entitlements', to='video.video')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'student', 'revoked_at'], name='video_inact_tenant__11c6f6_idx'), models.Index(fields=['enrollment', 'video'], name='video_inact_enrollm_a4ec04_idx'), models.Index(fields=['expires_at'], name='video_inact_expires_2da755_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('tenant', 'enrollment', 'video'), name='uniq_current_inactive_video_entitlement'), models.CheckConstraint(condition=models.Q(('access_mode', 'FREE_REVIEW'), ('access_mode', 'PROCTORED_CLASS'), _connector='OR'), name='inactive_video_entitlement_mode_valid'), models.CheckConstraint(condition=models.Q(('source', 'STAFF_AUTHORIZATION')), name='inactive_video_entitlement_source_valid'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('granted_at')), _connector='OR'), name='inactive_video_entitlement_expiry_valid'), models.CheckConstraint(condition=models.Q(('source_reference', ''), _negated=True), name='inactive_video_entitlement_source_ref_present'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='inactive_video_entitlement_reason_present'), models.CheckConstraint(condition=models.Q(('granted_by_reference', ''), _negated=True), name='inactive_video_entitlement_grant_ref_present'), models.CheckConstraint(condition=models.Q(models.Q(('revoke_reason', ''), ('revoked_at__isnull', True), ('revoked_by_reference', '')), models.Q(('revoked_at__isnull', False), models.Q(('revoked_by_reference', ''), _negated=True), models.Q(('revoke_reason', ''), _negated=True)), _connector='OR'), name='inactive_video_entitlement_revoke_meta_present')],
            },
        ),
    ]
