# Generated by Django 5.2.16 on 2026-08-29 13:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_tenant_controls_messaging_activation"),
        ("students", "0019_registration_request_student_history"),
        ("video", "0021_inactivevideoentitlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectVideoEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("STAFF_AUTHORIZATION", "교직원 명시 승인")],
                        max_length=32,
                    ),
                ),
                ("source_reference", models.CharField(max_length=128)),
                ("reason", models.TextField()),
                ("granted_by_reference", models.CharField(max_length=128)),
                (
                    "granted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_by_reference",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("revoke_reason", models.TextField(blank=True, default="")),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_direct_video_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_direct_video_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_video_entitlements",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_video_entitlements",
                        to="core.tenant",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_student_entitlements",
                        to="video.video",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "student", "revoked_at"],
                        name="video_direc_tenant__17c062_idx",
                    ),
                    models.Index(
                        fields=["video", "revoked_at"],
                        name="video_direc_video_i_113f0d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("tenant", "student", "video"),
                        name="uniq_current_direct_video_entitlement",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", "STAFF_AUTHORIZATION")),
                        name="direct_video_entitlement_source_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_reference", ""), _negated=True),
                        name="direct_video_entitlement_source_ref_present",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reason", ""), _negated=True),
                        name="direct_video_entitlement_reason_present",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("granted_by_reference", ""),
                            _negated=True,
                        ),
                        name="direct_video_entitlement_grant_ref_present",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("revoke_reason", ""),
                                ("revoked_at__isnull", True),
                                ("revoked_by_reference", ""),
                            ),
                            models.Q(
                                ("revoked_at__isnull", False),
                                models.Q(
                                    ("revoked_by_reference", ""),
                                    _negated=True,
                                ),
                                models.Q(("revoke_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="direct_video_entitlement_revoke_meta_present",
                    ),
                ],
            },
        ),
    ]
