# Generated by Django 5.2.16 on 2026-08-24 10:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_tenant_controls_messaging_activation'),
        ('teacher_app', '0002_pushsubscription_app_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherOpsExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='processing', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_ops_executions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ops_executions', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'actor_user', '-created_at'], name='teacher_ops_actor_idx')],
            },
        ),
    ]
