# Generated by Django 5.2.9 on 2026-01-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lectures", "0002_remove_session_exam"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cutline_percent", models.PositiveSmallIntegerField(default=80)),
                ("round_unit_percent", models.PositiveSmallIntegerField(default=5)),
                ("clinic_enabled", models.BooleanField(default=True)),
                ("clinic_on_fail", models.BooleanField(default=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_policy",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
