# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("homework_results", "0001_initial"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrollment_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="homework_results.homework",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_assignments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "homework_assignment",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "homework", "enrollment_id"),
                        name="uniq_homework_assignment_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomeworkEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(db_index=True)),
                ("enrollment_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_enrollments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "homework_enrollment",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "session_id", "enrollment_id"),
                        name="uniq_homework_enrollment_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HomeworkPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cutline_percent", models.PositiveSmallIntegerField(default=80)),
                ("round_unit_percent", models.PositiveSmallIntegerField(default=5)),
                ("clinic_enabled", models.BooleanField(default=True)),
                ("clinic_on_fail", models.BooleanField(default=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_policy",
                        to="lectures.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_policies",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "session"),
                        name="uniq_homework_policy_per_tenant_session",
                    )
                ],
            },
        ),
    ]
