# PATH: apps/domains/homework/migrations/0001_initial.py
# Generated by Django 5.2.x on 2026-01-18
#
# ✅ 설계 고정:
# - HomeworkScore는 "운영 입력 스냅샷"
# - 제출/채점 로직은 다른 도메인(submissions/results/progress) 책임

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkScore",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),

                ("enrollment_id", models.PositiveIntegerField(db_index=True)),

                ("score", models.FloatField(blank=True, null=True)),
                ("max_score", models.FloatField(blank=True, null=True)),
                ("teacher_approved", models.BooleanField(default=False)),
                ("passed", models.BooleanField(default=False)),

                ("is_locked", models.BooleanField(default=False)),
                (
                    "lock_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GRADING", "채점중"),
                            ("PUBLISHED", "게시됨"),
                            ("MANUAL", "수동잠금"),
                            ("OTHER", "기타"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),

                ("updated_by_user_id", models.PositiveIntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),

                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_scores",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="homeworkscore",
            constraint=models.UniqueConstraint(
                fields=("enrollment_id", "session"),
                name="unique_homework_score_per_enrollment_session",
            ),
        ),
        migrations.AddIndex(
            model_name="homeworkscore",
            index=models.Index(fields=["enrollment_id", "updated_at"], name="homework_hw_enroll_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworkscore",
            index=models.Index(fields=["session", "updated_at"], name="homework_hw_session_upd_idx"),
        ),
    ]
