# Generated by Django 5.2.9 on 2026-01-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.IntegerField(db_index=True)),
                ("enrollment_id", models.IntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "homework_enrollment",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_id", "enrollment_id"),
                        name="uniq_homework_enrollment_session_enrollment",
                    )
                ],
            },
        ),
    ]
