# Generated by Django 5.2.9 on 2026-02-04 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_attendance_expense_add_tenant"),
        ("homework", "0003_homework_assignment"),
        (
            "homework_results",
            "0008_remove_homeworkscore_unique_homework_score_per_enrollment_session",
        ),
        ("lectures", "0002_remove_session_exam"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="homeworkassignment",
            name="uniq_homework_assignment_homework_enrollment",
        ),
        migrations.RemoveConstraint(
            model_name="homeworkenrollment",
            name="uniq_homework_enrollment_session_enrollment",
        ),
        migrations.AddField(
            model_name="homeworkassignment",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_assignments",
                to="core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeworkenrollment",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_enrollments",
                to="core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeworkpolicy",
            name="tenant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_policies",
                to="core.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="homeworkassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "homework", "enrollment_id"),
                name="uniq_homework_assignment_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkenrollment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "session_id", "enrollment_id"),
                name="uniq_homework_enrollment_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkpolicy",
            constraint=models.UniqueConstraint(
                fields=("tenant", "session"),
                name="uniq_homework_policy_per_tenant_session",
            ),
        ),
    ]
