# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("teachers", "0004_make_teacher_tenant_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["tenant", "created_at"], name="teachers_te_tenant__c4e614_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teacher",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("tenant", "phone"),
                name="uniq_teacher_phone_per_tenant",
            ),
        ),
    ]
