# Generated by Django 5.1.3 on 2026-04-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0030_set_dnb_school_level_mode"),
        ("enrollment", "0001_initial"),
        ("lectures", "0006_p0_attempt_constraints"),
        ("students", "0011_school_level_mode_elementary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="비목 이름", max_length=120)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "수강료"),
                            ("TEXTBOOK", "교재비"),
                            ("REGISTRATION", "등록비"),
                            ("MATERIAL", "재료비"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "월납"), ("ONE_TIME", "일시납")],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField(help_text="기본 금액 (원)")),
                ("is_active", models.BooleanField(default=True)),
                ("memo", models.TextField(blank=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        help_text="특정 강의에 연결 (null이면 독립 비목)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_templates",
                        to="lectures.lecture",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_templates",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "fee_template",
            },
        ),
        migrations.CreateModel(
            name="StudentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adjusted_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="개별 조정 금액 (null이면 fee_template.amount 사용)",
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, help_text="할인 금액"),
                ),
                ("discount_reason", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        help_text="수강료인 경우 수강 등록과 연결",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_fees",
                        to="enrollment.enrollment",
                    ),
                ),
                (
                    "fee_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fees",
                        to="fees.feetemplate",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fees",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fees",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "student_fee",
            },
        ),
        migrations.CreateModel(
            name="StudentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="청구번호 (예: FEE-2026-04-0001)", max_length=40
                    ),
                ),
                (
                    "billing_year",
                    models.PositiveSmallIntegerField(help_text="청구 연도"),
                ),
                (
                    "billing_month",
                    models.PositiveSmallIntegerField(help_text="청구 월 (1-12)"),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(help_text="청구 총액 (원)"),
                ),
                (
                    "paid_amount",
                    models.PositiveIntegerField(default=0, help_text="납부 총액 (원)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "미납"),
                            ("PARTIAL", "부분납"),
                            ("PAID", "완납"),
                            ("OVERDUE", "연체"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(help_text="납부 기한")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, help_text="완납 일시", null=True),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="청구서 생성 직원 (자동 생성 시 null)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_invoices",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "student_invoice",
                "ordering": ["-billing_year", "-billing_month"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(help_text="항목명 (스냅샷)", max_length=200),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="금액 (할인 반영 후)"),
                ),
                (
                    "fee_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fees.feetemplate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_items",
                        to="core.tenant",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fees.studentinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "student_invoice_item",
            },
        ),
        migrations.CreateModel(
            name="FeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveIntegerField(help_text="납부 금액 (원)")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "카드"),
                            ("BANK_TRANSFER", "계좌이체"),
                            ("CASH", "현금"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "완료"),
                            ("CANCELLED", "취소"),
                            ("REFUNDED", "환불"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(help_text="납부 일시")),
                (
                    "receipt_note",
                    models.CharField(
                        blank=True, help_text="영수증 메모 / 입금자명", max_length=300
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="수납 기록 직원",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_payments",
                        to="core.tenant",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="fees.studentinvoice",
                    ),
                ),
            ],
            options={
                "db_table": "fee_payment",
                "ordering": ["-paid_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feetemplate",
            index=models.Index(
                fields=["tenant", "fee_type"], name="fee_templat_tenant__af1c06_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="feetemplate",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_fee_template_name_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["tenant", "student"], name="student_fee_tenant__ec5470_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentfee",
            constraint=models.UniqueConstraint(
                fields=("tenant", "student", "fee_template"),
                name="uniq_student_fee_per_template",
            ),
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["tenant", "status"], name="student_inv_tenant__f82174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["tenant", "student", "billing_year", "billing_month"],
                name="student_inv_tenant__e05af6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentinvoice",
            index=models.Index(
                fields=["due_date"], name="student_inv_due_dat_0e6844_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "invoice_number"),
                name="uniq_student_invoice_number_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentinvoice",
            constraint=models.UniqueConstraint(
                fields=("tenant", "student", "billing_year", "billing_month"),
                name="uniq_student_invoice_per_period",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["tenant", "invoice"], name="student_inv_tenant__419a82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["tenant", "student"], name="fee_payment_tenant__32c148_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["tenant", "invoice"], name="fee_payment_tenant__f49bf3_idx"
            ),
        ),
    ]
