# Generated by Django 5.1.3 on 2026-04-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feetemplate",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("TUITION", "수강료"),
                    ("TEXTBOOK", "교재비"),
                    ("HANDOUT", "판서/프린트"),
                    ("REGISTRATION", "등록비"),
                    ("MATERIAL", "재료비"),
                    ("OTHER", "기타"),
                ],
                max_length=20,
            ),
        ),
    ]
