# Generated by Django 5.1.3 on 2026-04-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_alter_feetemplate_fee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="feetemplate",
            name="auto_assign",
            field=models.BooleanField(
                default=True,
                help_text="수강 등록 시 자동 할당 여부 (False면 수동 할당만)",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="billing_end_month",
            field=models.CharField(
                blank=True,
                help_text="청구 종료월 (YYYY-MM, 비어있으면 제한 없음)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="billing_start_month",
            field=models.CharField(
                blank=True,
                help_text="청구 시작월 (YYYY-MM, 비어있으면 제한 없음)",
                max_length=7,
            ),
        ),
    ]
