# Generated by Django 5.1.3 on 2026-04-08 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_subscription_cancelled_status"),
        ("fees", "0003_feetemplate_auto_assign_studentfee_billing_end_month_and_more"),
        ("students", "0011_school_level_mode_elementary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feepayment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="클라이언트 제공 멱등성 키 (중복 납부 방지)",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="feepayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("tenant", "invoice", "idempotency_key"),
                name="uniq_fee_payment_idempotency_key",
            ),
        ),
    ]
