#!/usr/bin/env python
"""
배포용 .env 생성 — .env.admin97 기반, RDS 연결값으로 DB_* 매핑

사용법:
  python scripts/prepare_deploy_env.py [--output .env.deploy]
  → 출력: .env.deploy (EC2에 복사 후 .env로 사용)
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ADMIN_FILE = ROOT / ".env.admin97"

# RDS 배포 시: DB_*_RDS → DB_* 로 매핑
RDS_MAP = {
    "DB_HOST_RDS": "DB_HOST",
    "DB_NAME_RDS": "DB_NAME",
    "DB_USER_RDS": "DB_USER",
    "DB_PASSWORD_RDS": "DB_PASSWORD",
    "DB_PORT_RDS": "DB_PORT",
}

# 배포 시 제외할 키 (로컬 전용)
EXCLUDE = {"DB_HOST", "DB_NAME", "DB_USER", "DB_PASSWORD", "DB_PORT"}


def parse_env(content: str) -> dict[str, str]:
    out = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$", line)
        if m:
            key, val = m.group(1), m.group(2)
            val = val.strip()
            if val.startswith('"') and val.endswith('"'):
                val = val[1:-1].replace('\\"', '"')
            out[key] = val
    return out


def main():
    ap = argparse.ArgumentParser(description="Generate deployment .env from .env.admin97")
    ap.add_argument("--output", "-o", default=".env.deploy", help="Output file path")
    args = ap.parse_args()

    if not ADMIN_FILE.exists():
        print(f"ERROR: {ADMIN_FILE} not found")
        return 1

    raw = ADMIN_FILE.read_text(encoding="utf-8")
    env = parse_env(raw)

    # RDS 값으로 DB_* 덮어쓰기
    for src, dst in RDS_MAP.items():
        if src in env:
            env[dst] = env[src]

    # 로컬 DB_* (RDS 배포 시 불필요) 제거는 안 함 — RDS_MAP으로 이미 덮어씀

    lines = []
    lines.append("# Generated by scripts/prepare_deploy_env.py — DO NOT COMMIT")
    lines.append("# EC2에 복사 후 .env 로 사용")
    lines.append("")
    for k, v in sorted(env.items()):
        if k in EXCLUDE and k in RDS_MAP.values():
            pass  # 이미 RDS로 매핑됨
        if k.endswith("_RDS"):
            continue
        if k in ("AWS_ACCOUNT_ID", "ECR_REGISTRY"):
            continue
        lines.append(f"{k}={v}")
    lines.append("")

    out_path = Path(args.output)
    if not out_path.is_absolute():
        out_path = ROOT / out_path
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Written: {out_path}")
    return 0


if __name__ == "__main__":
    exit(main())
