# Generated by Django 5.2.9 on 2026-01-06 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("parents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남"), ("F", "여")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "1"), (2, "2"), (3, "3")], null=True
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[("MIDDLE", "중등"), ("HIGH", "고등")],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "parent_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "high_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "high_school_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "middle_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("is_managed", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="parents.parent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="학생이 로그인 계정을 가지는 경우 연결",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#000000", max_length=20)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="uniq_tag_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_tags",
                        to="students.student",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="students.StudentTag",
                to="students.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttag",
            constraint=models.UniqueConstraint(
                fields=("student", "tag"), name="uniq_student_tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="uniq_student_user",
            ),
        ),
    ]
