# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("parents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ps_number",
                    models.CharField(help_text="PS 번호 (학원 학생 ID)", max_length=20),
                ),
                (
                    "omr_code",
                    models.CharField(
                        help_text="OMR 자동채점 식별자 (학생 전화번호 또는 부모 전화번호 뒤 8자리)",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남"), ("F", "여")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "1"), (2, "2"), (3, "3")], null=True
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        choices=[("MIDDLE", "중등"), ("HIGH", "고등")],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "parent_phone",
                    models.CharField(
                        help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                        max_length=20,
                    ),
                ),
                (
                    "uses_identifier",
                    models.BooleanField(
                        default=False,
                        help_text="True면 학생 전화 없음, 식별자(010+8자리)로 가입. 표시 시 '식별자 XXXX-XXXX'",
                    ),
                ),
                (
                    "high_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "high_school_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "middle_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("memo", models.TextField(blank=True, null=True)),
                ("is_managed", models.BooleanField(default=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="학생이 학생앱에서 업로드한 프로필 사진",
                        null=True,
                        upload_to="student_profile/%Y/%m/",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="삭제일시. 설정 시 30일 보관 후 자동 삭제",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="parents.parent",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="소속 학원 (Tenant)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="학생 로그인 계정 (필수)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#000000", max_length=20)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="uniq_tag_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_tags",
                        to="students.student",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.tag"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="students",
                through="students.StudentTag",
                to="students.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttag",
            constraint=models.UniqueConstraint(
                fields=("student", "tag"), name="uniq_student_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "created_at"], name="students_st_tenant__c32d68_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uniq_student_user_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "ps_number"), name="uniq_student_ps_number_per_tenant"
            ),
        ),
    ]
