# Generated by Django 5.1.3 on 2026-03-07 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_clinic_idcard_colors"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("approved", "승인됨"),
                            ("rejected", "거절"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("initial_password", models.CharField(max_length=128)),
                ("parent_phone", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("school_type", models.CharField(default="HIGH", max_length=10)),
                (
                    "high_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "middle_school",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "high_school_class",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("major", models.CharField(blank=True, max_length=50, null=True)),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=1, null=True)),
                ("memo", models.TextField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registration_request",
                        to="students.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_registration_requests",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"],
                        name="students_st_tenant__d0efca_idx",
                    )
                ],
            },
        ),
    ]
