# Generated by Django 5.2.9 on 2026-02-04 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_attendance_expense_add_tenant"),
        ("parents", "0001_initial"),
        ("students", "0002_add_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="uniq_student_user",
        ),
        migrations.AlterField(
            model_name="student",
            name="tenant",
            field=models.ForeignKey(
                help_text="소속 학원 (Tenant)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="core.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("tenant", "user"),
                name="uniq_student_user_per_tenant",
            ),
        ),
    ]
