# Generated by Django 5.2.9 on 2026-02-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_make_attendance_expense_tenant_not_null"),
        ("parents", "0004_make_parent_tenant_not_null"),
        ("students", "0003_remove_student_uniq_student_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="uniq_student_user_per_tenant",
        ),
        migrations.AddField(
            model_name="student",
            name="omr_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="ps_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                help_text="학생 로그인 계정 (필수)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "user"), name="uniq_student_user_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "ps_number"), name="uniq_student_ps_number_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("tenant", "omr_code"), name="uniq_student_omr_code_per_tenant"
            ),
        ),
    ]
