# Generated by Django 5.2.9 on 2026-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_uniq_student_user_per_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="omr_code",
            field=models.CharField(
                help_text="OMR 자동채점 식별자 (전화번호 뒤 8자리)", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="ps_number",
            field=models.CharField(help_text="PS 번호 (학원 학생 ID)", max_length=20),
        ),
    ]
