# Generated by Django 5.1.3 on 2026-03-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_add_registration_request_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_photo_r2_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="R2에 저장된 프로필 사진 키. 설정 시 profile_photo 대신 사용",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="학생이 학생앱에서 업로드한 프로필 사진 (레거시 로컬)",
                null=True,
                upload_to="student_profile/%Y/%m/",
            ),
        ),
    ]
