# Generated by Django 5.2.9 on 2026-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_add_student_uses_identifier"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="uniq_student_omr_code_per_tenant",
        ),
        migrations.AlterField(
            model_name="student",
            name="omr_code",
            field=models.CharField(
                help_text="OMR 자동채점 식별자 (학생 전화번호 또는 부모 전화번호 뒤 8자리)",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
