# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("parents", "0006_alter_parent_phone_and_more"),
        ("students", "0008_make_phone_nullable_remove_omr_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["tenant", "created_at"], name="students_st_tenant__c32d68_idx"
            ),
        ),
    ]
