# Generated by Django 5.1.3 on 2026-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_add_initial_password_plain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="ps_number",
            field=models.CharField(help_text="PS 번호 (학원 학생 ID)", max_length=50),
        ),
    ]
