# Generated by Django 5.1.3 on 2026-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_extend_ps_number_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="elementary_school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentregistrationrequest",
            name="elementary_school",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="school_type",
            field=models.CharField(
                choices=[("ELEMENTARY", "초등"), ("MIDDLE", "중등"), ("HIGH", "고등")],
                default="HIGH",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="studentregistrationrequest",
            name="school_type",
            field=models.CharField(default="HIGH", max_length=12),
        ),
    ]
