# Generated by Django 5.2.16 on 2026-08-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_student_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pending_account_notice_parent_password_ciphertext",
            field=models.TextField(
                blank=True,
                default="",
                help_text="첫 수강 확정 시 계정 안내에 사용할 학부모 비밀번호 안내값의 암호문",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pending_account_notice_since",
            field=models.DateTimeField(
                blank=True,
                help_text="학생 생성 후 첫 실제 수강 확정을 기다리는 계정 안내 생성 시각",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pending_account_notice_student_password_ciphertext",
            field=models.TextField(
                blank=True,
                default="",
                help_text="첫 수강 확정 시 계정 안내에 사용할 학생 비밀번호 안내값의 암호문",
                null=True,
            ),
        ),
    ]
