# Generated by Django 5.2.16 on 2026-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "students",
            "0016_student_pending_account_notice_parent_password_ciphertext_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pending_account_notice_origin_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="첫 수강 계정 안내를 만든 job/batch 식별자",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="pending_account_notice_origin_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="첫 수강 계정 안내를 만든 원천 종류(excel_import 등)",
                max_length=64,
            ),
        ),
    ]
