# Generated by Django 5.2.9 on 2026-01-06 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("completed_sessions", models.PositiveIntegerField(default=0)),
                ("failed_sessions", models.PositiveIntegerField(default=0)),
                ("consecutive_failed_sessions", models.PositiveIntegerField(default=0)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("WARNING", "Warning"),
                            ("DANGER", "Danger"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "last_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_lecture_progress_rows",
                        to="lectures.session",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progress_rows",
                        to="lectures.lecture",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProgressPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("video_required_rate", models.PositiveIntegerField(default=90)),
                ("exam_start_session_order", models.PositiveIntegerField(default=2)),
                ("exam_end_session_order", models.PositiveIntegerField(default=9999)),
                ("exam_pass_score", models.FloatField(default=60.0)),
                (
                    "homework_start_session_order",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "homework_end_session_order",
                    models.PositiveIntegerField(default=9999),
                ),
                (
                    "homework_pass_type",
                    models.CharField(
                        choices=[
                            ("SUBMIT", "제출만"),
                            ("SCORE", "점수"),
                            ("TEACHER_APPROVAL", "강사승인"),
                        ],
                        default="TEACHER_APPROVAL",
                        max_length=30,
                    ),
                ),
                (
                    "lecture",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_policy",
                        to="lectures.lecture",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ClinicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enrollment_id", models.PositiveIntegerField(db_index=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("AUTO_FAILED", "자동(차시 미통과)"),
                            ("AUTO_RISK", "자동(위험 알림)"),
                            ("MANUAL_REQUEST", "수동(학생/학부모 요청)"),
                            ("TEACHER_RECOMMEND", "강사 추천"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_auto", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("memo", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_links",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["enrollment_id", "created_at"],
                        name="progress_cl_enrollm_ec562f_idx",
                    ),
                    models.Index(
                        fields=["session", "created_at"],
                        name="progress_cl_session_8934be_idx",
                    ),
                    models.Index(
                        fields=["reason"], name="progress_cl_reason_441a74_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enrollment_id", models.PositiveIntegerField(db_index=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("WARNING", "Warning"), ("DANGER", "Danger")],
                        max_length=10,
                    ),
                ),
                (
                    "rule",
                    models.CharField(
                        choices=[
                            ("CONSECUTIVE_INCOMPLETE", "연속 미완료"),
                            ("CONSECUTIVE_LOW_SCORE", "연속 저점수"),
                            ("OTHER", "기타"),
                        ],
                        max_length=40,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_logs",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["enrollment_id", "created_at"],
                        name="progress_ri_enrollm_768c23_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "created_at"],
                        name="progress_ri_risk_le_e55884_idx",
                    ),
                    models.Index(
                        fields=["rule", "created_at"],
                        name="progress_ri_rule_249149_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enrollment_id", models.PositiveIntegerField(db_index=True)),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("video_progress_rate", models.PositiveIntegerField(default=0)),
                ("video_completed", models.BooleanField(default=False)),
                ("exam_score", models.FloatField(blank=True, null=True)),
                ("exam_passed", models.BooleanField(default=False)),
                ("homework_submitted", models.BooleanField(default=False)),
                ("homework_passed", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_rows",
                        to="lectures.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enrollment_id", "session"),
                        name="unique_session_progress_per_enrollment",
                    )
                ],
            },
        ),
    ]
