# Generated by Django 5.x on YYYY-MM-DD HH:MM
# PATH: apps/domains/progress/migrations/0002_add_cliniclink_resolved_at.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliniclink",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="cliniclink",
            index=models.Index(
                fields=["resolved_at"],
                name="progress_cliniclink_resolved_at_idx",
            ),
        ),
    ]
