# Generated by Django 5.2.9 on 2026-02-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_add_cliniclink_resolved_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cliniclink",
            new_name="progress_cl_resolve_c64305_idx",
            old_name="progress_cliniclink_resolved_at_idx",
        ),
    ]
