# Generated by Django 5.2.9 on 2026-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0004_remove_sessionprogress_exam_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresspolicy",
            name="exam_aggregate_strategy",
            field=models.CharField(
                choices=[("MAX", "최고점"), ("AVG", "평균"), ("LATEST", "최근 제출")],
                default="MAX",
                help_text="Session에 여러 시험이 있을 때 Result 집계 방식",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="progresspolicy",
            name="exam_pass_source",
            field=models.CharField(
                choices=[("POLICY", "정책 기준"), ("EXAM", "시험 기준")],
                default="EXAM",
                help_text="합격 기준을 정책(POLICY)으로 볼지, 시험(EXAM)마다 볼지",
                max_length=10,
            ),
        ),
    ]
