# Generated by Django 5.1.3 on 2026-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("lectures", "0002_lecture_is_system"),
        ("progress", "0005_cliniclink_source_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cliniclink",
            name="uniq_cliniclink_per_source_cycle",
        ),
        migrations.RenameIndex(
            model_name="cliniclink",
            new_name="progress_cl_resolut_05d424_idx",
            old_name="progress_cl_resolut_idx",
        ),
        migrations.RenameIndex(
            model_name="cliniclink",
            new_name="progress_cl_source__80807e_idx",
            old_name="progress_cl_source__b9f3c7_idx",
        ),
        migrations.AddConstraint(
            model_name="cliniclink",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_id__isnull", False), ("source_type__isnull", False)
                ),
                fields=(
                    "enrollment",
                    "session",
                    "source_type",
                    "source_id",
                    "cycle_no",
                ),
                name="uniq_cliniclink_per_source_cycle",
            ),
        ),
    ]
