# Generated by Django 5.1.3 on 2026-04-07 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_set_dnb_school_level_mode"),
        (
            "progress",
            "0006_remove_cliniclink_uniq_cliniclink_per_source_cycle_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliniclink",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinic_links",
                to="core.tenant",
            ),
        ),
    ]
