# Generated by Django 5.1.3 on 2026-05-24 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("progress", "0010_cliniclink_resolution_history_and_carried_over"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lectureprogress",
            name="enrollment",
            field=models.OneToOneField(
                db_column="enrollment_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture_progress_rows",
                to="enrollment.enrollment",
            ),
        ),
    ]
