# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_manager", models.BooleanField(default=False)),
                (
                    "pay_type",
                    models.CharField(
                        choices=[("HOURLY", "시급"), ("MONTHLY", "월급")],
                        default="HOURLY",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staffs",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayrollSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "work_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("work_amount", models.PositiveIntegerField(default=0)),
                ("approved_expense_amount", models.PositiveIntegerField(default=0)),
                ("total_amount", models.PositiveIntegerField(default=0)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_snapshots",
                        to="core.tenant",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_snapshots",
                        to="staffs.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("amount", models.PositiveIntegerField()),
                ("memo", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "반려"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_records",
                        to="core.tenant",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_records",
                        to="staffs.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkMonthLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("is_locked", models.BooleanField(default=True)),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_work_months",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_month_locks",
                        to="staffs.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_month_locks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("base_hourly_wage", models.PositiveIntegerField(default=0)),
                (
                    "color",
                    models.CharField(
                        default="#4CAF50", help_text="HEX 색상 코드", max_length=7
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_types",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("break_minutes", models.PositiveIntegerField(default=0)),
                (
                    "current_break_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resolved_hourly_wage",
                    models.PositiveIntegerField(
                        blank=True, help_text="급여 계산에 실제 사용된 시급", null=True
                    ),
                ),
                ("memo", models.TextField(blank=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_records",
                        to="staffs.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_records",
                        to="core.tenant",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_records",
                        to="staffs.worktype",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="StaffWorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hourly_wage",
                    models.PositiveIntegerField(
                        blank=True, help_text="비우면 WorkType 기본 단가", null=True
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_work_types",
                        to="staffs.staff",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_work_types",
                        to="core.tenant",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_work_types",
                        to="staffs.worktype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "created_at"], name="staffs_staf_tenant__70adad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("tenant", "phone"),
                name="uniq_staff_phone_per_tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollsnapshot",
            unique_together={("tenant", "staff", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="workmonthlock",
            unique_together={("tenant", "staff", "year", "month")},
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["tenant", "date"], name="staffs_work_tenant__40a0f0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffworktype",
            unique_together={("tenant", "staff", "work_type")},
        ),
    ]
