# Generated by Django 5.1.3 on 2026-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0004_workrecord_break_total_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="선생님 프로필 사진",
                null=True,
                upload_to="staff_profile/%Y/%m/",
            ),
        ),
    ]
