# Generated by Django 5.2.9 on 2026-02-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_make_attendance_expense_tenant_not_null"),
        ("staffs", "0005_add_staffs_tenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="payrollsnapshot",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="staffworktype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="workmonthlock",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="expenserecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_records",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="payrollsnapshot",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payroll_snapshots",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffs",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="staffworktype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_work_types",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="workmonthlock",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_month_locks",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="workrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_records",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="worktype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_types",
                to="core.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="payrollsnapshot",
            unique_together={("tenant", "staff", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="staffworktype",
            unique_together={("tenant", "staff", "work_type")},
        ),
        migrations.AlterUniqueTogether(
            name="workmonthlock",
            unique_together={("tenant", "staff", "year", "month")},
        ),
    ]
