# Generated by Django 5.2.9 on 2026-02-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0006_alter_payrollsnapshot_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="current_break_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workrecord",
            name="resolved_hourly_wage",
            field=models.PositiveIntegerField(
                blank=True, help_text="급여 계산에 실제 사용된 시급", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffworktype",
            name="hourly_wage",
            field=models.PositiveIntegerField(
                blank=True, help_text="비우면 WorkType 기본 단가", null=True
            ),
        ),
        migrations.AlterField(
            model_name="workrecord",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
