# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("staffs", "0007_workrecord_current_break_started_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="정규화된 전화번호 (하이픈 제거, 예: 01012345678)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["tenant", "created_at"], name="staffs_staf_tenant__70adad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workrecord",
            index=models.Index(
                fields=["tenant", "date"], name="staffs_work_tenant__40a0f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staff",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("phone__isnull", False), models.Q(("phone", ""), _negated=True)
                ),
                fields=("tenant", "phone"),
                name="uniq_staff_phone_per_tenant",
            ),
        ),
    ]
