# Generated by Django 5.2.16 on 2026-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0009_staff_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="workrecord",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="실제 퇴근 날짜. 기존 미기록 자료는 익일 퇴근 추론을 유지합니다.",
                null=True,
            ),
        ),
    ]
