# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enrollment", "0001_initial"),
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("template", "Template"), ("regular", "Regular")],
                        default="regular",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("allow_retake", models.BooleanField(default=False)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("pass_score", models.FloatField(default=0.0)),
                ("open_at", models.DateTimeField(blank=True, null=True)),
                ("close_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sessions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="이 시험이 속한 차시들",
                        related_name="exams",
                        to="lectures.session",
                    ),
                ),
                (
                    "template_exam",
                    models.ForeignKey(
                        blank=True,
                        help_text="regular 시험이 참조하는 template 시험",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_exams",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answers",
                    models.JSONField(
                        help_text="key=ExamQuestion.id (string), value=correct answer"
                    ),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_key",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_answer_key",
            },
        ),
        migrations.CreateModel(
            name="ExamAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("problem_pdf", "Problem PDF"),
                            ("omr_sheet", "OMR Sheet"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_key", models.CharField(max_length=512)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam_asset",
            },
        ),
        migrations.CreateModel(
            name="ExamEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_enrollments",
                        to="enrollment.enrollment",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_enrollments",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam_enrollment",
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="MAIN", max_length=50)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="exams/sheets/"),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_sheet",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("score", models.FloatField(default=1.0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exams/questions/"
                    ),
                ),
                ("region_meta", models.JSONField(blank=True, null=True)),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.sheet",
                    ),
                ),
            ],
            options={
                "db_table": "exams_question",
                "ordering": ["number"],
            },
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("exam_type", "template"), _negated=True),
                    ("template_exam__isnull", True),
                    _connector="OR",
                ),
                name="exams_exam_template_has_no_template_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("exam_type", "regular"), _negated=True),
                    ("template_exam__isnull", False),
                    _connector="OR",
                ),
                name="exams_exam_regular_requires_template_exam",
            ),
        ),
        migrations.AddIndex(
            model_name="examasset",
            index=models.Index(
                fields=["exam", "asset_type"], name="exams_exam__exam_id_1b856d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examasset",
            unique_together={("exam", "asset_type")},
        ),
        migrations.AlterUniqueTogether(
            name="examenrollment",
            unique_together={("exam", "enrollment")},
        ),
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together={("sheet", "number")},
        ),
    ]
