# Generated by Django 5.2.9 on 2025-12-19 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=100)),
                ("exam_type", models.CharField(default="regular", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "exams_exam",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answers", models.JSONField()),
                (
                    "exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_key",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_answer_key",
            },
        ),
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="exams/sheets/"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_sheet",
                "unique_together": {("exam", "name")},
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("score", models.FloatField(default=1.0)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="exams/questions/"
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.sheet",
                    ),
                ),
            ],
            options={
                "db_table": "exams_question",
                "ordering": ["number"],
                "unique_together": {("sheet", "number")},
            },
        ),
    ]
