# Generated by Django 5.1.3 on 2026-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
