# Generated by Django 5.1.3 on 2026-03-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_exam_subject_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "초안"), ("OPEN", "진행중"), ("CLOSED", "마감")],
                db_index=True,
                default="DRAFT",
                help_text="과제와 동일: 생성=DRAFT, 진행하기=OPEN, 마감=CLOSED. 사용자에는 설정 중/진행 중/마감으로만 노출.",
                max_length=20,
            ),
        ),
    ]
