# Generated by Django 5.2.9 on 2026-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_exam_policy_and_assets"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="examasset",
            new_name="exams_exam__exam_id_1b856d_idx",
            old_name="exams_examasset_exam_asset_type_idx",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="region_meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="examasset",
            name="asset_type",
            field=models.CharField(
                choices=[("problem_pdf", "Problem PDF"), ("omr_sheet", "OMR Sheet")],
                max_length=30,
            ),
        ),
    ]
