# Generated by Django 5.2.9 on 2026-01-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exams",
            "0003_rename_exams_examasset_exam_asset_type_idx_exams_exam__exam_id_1b856d_idx_and_more",
        ),
        ("lectures", "0002_remove_session_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="sessions",
            field=models.ManyToManyField(
                blank=True,
                help_text="이 시험이 속한 차시들",
                related_name="exams",
                to="lectures.session",
            ),
        ),
        migrations.AlterField(
            model_name="answerkey",
            name="answers",
            field=models.JSONField(
                help_text="key=ExamQuestion.id (string), value=correct answer"
            ),
        ),
    ]
