# Generated by Django 5.2.9 on 2026-01-23 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0001_initial"),
        ("exams", "0004_exam_sessions_alter_answerkey_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_enrollments",
                        to="enrollment.enrollment",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_enrollments",
                        to="exams.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exams_exam_enrollment",
                "unique_together": {("exam", "enrollment")},
            },
        ),
    ]
