# Generated by Django 5.2.9 on 2026-01-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_examenrollment"),
        ("lectures", "0002_remove_session_exam"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sheet",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="exam",
            name="template_exam",
            field=models.ForeignKey(
                blank=True,
                help_text="regular 시험이 참조하는 template 시험",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_exams",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("template", "Template"), ("regular", "Regular")],
                default="regular",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="exam",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sheet",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="sheet",
            name="name",
            field=models.CharField(default="MAIN", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("exam_type", "template"), _negated=True),
                    ("template_exam__isnull", True),
                    _connector="OR",
                ),
                name="exams_exam_template_has_no_template_exam",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("exam_type", "regular"), _negated=True),
                    ("template_exam__isnull", False),
                    _connector="OR",
                ),
                name="exams_exam_regular_requires_template_exam",
            ),
        ),
    ]
