# Generated by Django 5.1.3 on 2026-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_status_default_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="answer_visibility",
            field=models.CharField(
                choices=[
                    ("hidden", "비공개"),
                    ("after_closed", "마감 후 공개"),
                    ("always", "항상 공개"),
                ],
                default="hidden",
                help_text="정답 공개 정책: hidden=비공개, after_closed=마감 후 공개, always=항상 공개",
                max_length=20,
            ),
        ),
    ]
