# Generated by Django 5.1.3 on 2026-03-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_program_legal_fields"),
        ("exams", "0007_add_answer_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="이 시험이 속한 학원. template exam의 tenant isolation 보장.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="core.tenant",
            ),
        ),
    ]
