# Generated by Django 5.1.3 on 2026-04-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_set_dnb_school_level_mode"),
        ("exams", "0013_exam_tenant_not_null"),
        ("homework_results", "0008_hwscore_non_negative_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="묶음 이름", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_bundles",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "exams_template_bundle",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateBundleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("exam", "시험"), ("homework", "과제")], max_length=20
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="적용 시 사용할 제목 (비어있으면 템플릿 제목 사용)",
                        max_length=255,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        help_text="max_score, pass_score 등 적용 시 설정값",
                        null=True,
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="exams.templatebundle",
                    ),
                ),
                (
                    "exam_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="시험 템플릿 (item_type=exam 일 때)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundle_items",
                        to="exams.exam",
                    ),
                ),
                (
                    "homework_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="과제 템플릿 (item_type=homework 일 때)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bundle_items",
                        to="homework_results.homework",
                    ),
                ),
            ],
            options={
                "db_table": "exams_template_bundle_item",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
