# Generated by Django 5.1.3 on 2026-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_set_dnb_school_level_mode"),
        ("exams", "0014_template_bundle"),
        ("lectures", "0006_p0_attempt_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1)),
                name="exams_exam_max_attempts_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("pass_score__lte", models.F("max_score"))),
                name="exams_exam_pass_lte_max",
            ),
        ),
    ]
