# Generated by Django 5.1.3 on 2026-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0015_p0_attempt_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "초안"), ("OPEN", "진행중"), ("CLOSED", "마감")],
                default="OPEN",
                help_text="Legacy compatibility storage. Business logic uses exam_type + is_active + session link.",
                max_length=20,
            ),
        ),
    ]
