# Generated by Django 5.2.16 on 2026-08-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0022_examasset_teacher_explanation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examasset",
            name="file_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
