# Generated by Django 5.2.9 on 2026-02-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("exam", "Exam"), ("homework", "Homework")],
                        max_length=20,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("omr_scan", "OMR Scan"),
                            ("omr_manual", "OMR Manual Input"),
                            ("online", "Online"),
                            ("homework_image", "Homework Image"),
                            ("homework_video", "Homework Video"),
                            ("ai_match", "AI Image Match"),
                        ],
                        max_length=30,
                    ),
                ),
                ("file_key", models.CharField(blank=True, max_length=512, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("dispatched", "Dispatched"),
                            ("extracting", "Extracting"),
                            ("answers_ready", "Answers Ready"),
                            ("grading", "Grading"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("needs_identification", "Needs Identification"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_question_id",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Fixed contract: exams.ExamQuestion.id"
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="submissions.submission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_answers",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_submissionanswer",
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="submissions_target__6e8ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["enrollment_id", "created_at"],
                name="submissions_enrollm_bf0086_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "created_at"], name="submissions_user_id_6a1f53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_c2b4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["source"], name="submissions_source_234254_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["tenant", "created_at"], name="submissions_tenant__da4eb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["exam_question_id"], name="submissions_exam_qu_5bbab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission", "exam_question_id"],
                name="submissions_submiss_2a9caf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissionanswer",
            unique_together={("submission", "exam_question_id")},
        ),
    ]
