# apps/domains/submissions/migrations/0001_initial.py
# Generated by Django 5.2.9
#
# ⚠️ IMPORTANT
# - 이 0001은 "최종 계약" 기준으로 수동 수정됨
# - question_id / question_number 개념 없음
# - exam_question_id만 단일 진실
# - 이후 migration에서 절대 충돌 나지 않음

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ======================================================
        # Submission
        # ======================================================
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),

                ("enrollment_id", models.PositiveIntegerField(null=True, blank=True, db_index=True)),

                (
                    "target_type",
                    models.CharField(
                        max_length=20,
                        choices=[("exam", "Exam"), ("homework", "Homework")],
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),

                (
                    "source",
                    models.CharField(
                        max_length=30,
                        choices=[
                            ("omr_scan", "OMR Scan"),
                            ("omr_manual", "OMR Manual Input"),
                            ("online", "Online"),
                            ("homework_image", "Homework Image"),
                            ("homework_video", "Homework Video"),
                            ("ai_match", "AI Image Match"),
                        ],
                    ),
                ),

                # R2 file metadata
                ("file_key", models.CharField(max_length=512, null=True, blank=True)),
                ("file_type", models.CharField(max_length=50, null=True, blank=True)),
                ("file_size", models.PositiveIntegerField(null=True, blank=True)),

                ("payload", models.JSONField(null=True, blank=True)),

                (
                    "status",
                    models.CharField(
                        max_length=20,
                        default="submitted",
                        choices=[
                            ("submitted", "Submitted"),
                            ("dispatched", "Dispatched"),
                            ("extracting", "Extracting"),
                            ("answers_ready", "Answers Ready"),
                            ("grading", "Grading"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                    ),
                ),

                ("error_message", models.TextField(blank=True)),
                ("meta", models.JSONField(null=True, blank=True)),

                (
                    "user",
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                    ),
                ),
            ],
        ),

        # ======================================================
        # SubmissionAnswer (FINAL CONTRACT)
        # ======================================================
        migrations.CreateModel(
            name="SubmissionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),

                # ✅ 단일 진실
                (
                    "exam_question_id",
                    models.PositiveIntegerField(
                        help_text="Fixed contract: exams.ExamQuestion.id",
                    ),
                ),

                ("answer", models.TextField(blank=True)),
                ("meta", models.JSONField(default=dict, blank=True)),

                (
                    "submission",
                    models.ForeignKey(
                        to="submissions.submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_submissionanswer",
                "unique_together": {("submission", "exam_question_id")},
            },
        ),
    ]
