# Generated by Django 5.1.3 on 2026-03-13 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_program_billing_mode_program_cancel_at_period_end_and_more"),
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "submitted",
                            "dispatched",
                            "extracting",
                            "answers_ready",
                            "grading",
                            "done",
                        ],
                    )
                ),
                fields=("user", "target_type", "target_id"),
                name="unique_active_submission_per_target",
            ),
        ),
    ]
