# Generated by Django 5.2.9 on 2026-02-01 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionanswer",
            name="exam_question_id",
            field=models.PositiveIntegerField(
                db_index=True, help_text="Fixed contract: exams.ExamQuestion.id"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="submissions_target__6e8ca2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["enrollment_id", "created_at"],
                name="submissions_enrollm_bf0086_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "created_at"], name="submissions_user_id_6a1f53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_c2b4f2_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["source"], name="submissions_source_234254_idx"),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["exam_question_id"], name="submissions_exam_qu_5bbab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submissionanswer",
            index=models.Index(
                fields=["submission", "exam_question_id"],
                name="submissions_submiss_2a9caf_idx",
            ),
        ),
    ]
