# Generated by Django 5.1.3 on 2026-03-17 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_program_legal_fields"),
        ("submissions", "0002_unique_active_submission_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="submission",
            name="unique_active_submission_per_target",
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("dispatched", "Dispatched"),
                    ("extracting", "Extracting"),
                    ("answers_ready", "Answers Ready"),
                    ("grading", "Grading"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("needs_identification", "Needs Identification"),
                    ("superseded", "Superseded"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "submitted",
                            "dispatched",
                            "extracting",
                            "answers_ready",
                            "grading",
                        ],
                    )
                ),
                fields=("user", "target_type", "target_id"),
                name="unique_active_submission_per_target",
            ),
        ),
    ]
