# Generated by Django 5.2.9 on 2026-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_alter_submissionanswer_exam_question_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("dispatched", "Dispatched"),
                    ("extracting", "Extracting"),
                    ("answers_ready", "Answers Ready"),
                    ("grading", "Grading"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("needs_identification", "Needs Identification"),
                ],
                default="submitted",
                max_length=30,
            ),
        ),
    ]
