# Generated by Django 5.2.12 on 2026-03-24 02:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_program_legal_fields'),
        ('submissions', '0003_add_superseded_status_and_fix_retake_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='submission',
            name='unique_active_submission_per_target',
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('source__in', ['online', 'omr_manual', 'homework_image', 'homework_video', 'ai_match']), ('status__in', ['submitted', 'dispatched', 'extracting', 'answers_ready', 'grading'])), fields=('user', 'target_type', 'target_id'), name='unique_active_submission_per_target'),
        ),
    ]
