# Generated by Django 5.1.3 on 2026-06-01 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_pending_password_reset"),
        ("submissions", "0004_allow_multiple_omr_scan_submissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="OMRRecognitionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("worker_version", models.CharField(blank=True, max_length=32)),
                ("answer_count", models.PositiveIntegerField(default=0)),
                ("answer_status_counts", models.JSONField(blank=True, default=dict)),
                ("aligned", models.BooleanField(blank=True, null=True)),
                ("alignment_method", models.CharField(blank=True, max_length=64)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_recognition_runs",
                        to="submissions.submission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_recognition_runs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_omr_recognition_run",
            },
        ),
        migrations.CreateModel(
            name="OMRDetectedAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_number", models.PositiveIntegerField(db_index=True)),
                (
                    "exam_question_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("answer", models.TextField(blank=True)),
                ("detected", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(blank=True, db_index=True, max_length=32)),
                ("marking", models.CharField(blank=True, max_length=64)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_detected_answers",
                        to="submissions.submission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_detected_answers",
                        to="core.tenant",
                    ),
                ),
                (
                    "recognition_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_answers",
                        to="submissions.omrrecognitionrun",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_omr_detected_answer",
            },
        ),
        migrations.CreateModel(
            name="OMRStudentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment_id",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("needs_review", "Needs Review"),
                            ("unmatched", "Unmatched"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=32,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("auto_identifier", "Auto Identifier"),
                            ("manual", "Manual"),
                            ("preserved_manual", "Preserved Manual"),
                        ],
                        db_index=True,
                        default="auto_identifier",
                        max_length=32,
                    ),
                ),
                ("identifier_status", models.CharField(blank=True, max_length=64)),
                ("identifier_payload", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("actor", models.CharField(blank=True, max_length=128)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                (
                    "matched_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_student_matches",
                        to="submissions.submission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_student_matches",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "submissions_omr_student_match",
            },
        ),
        migrations.AddIndex(
            model_name="omrrecognitionrun",
            index=models.Index(
                fields=["tenant", "submission", "-received_at"],
                name="submissions_tenant__0c0b7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="omrrecognitionrun",
            index=models.Index(
                fields=["status", "received_at"], name="submissions_status_d50ab4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omrrecognitionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_id", ""), _negated=True),
                fields=("submission", "job_id"),
                name="uniq_omr_recognition_submission_job",
            ),
        ),
        migrations.AddIndex(
            model_name="omrdetectedanswer",
            index=models.Index(
                fields=["submission", "question_number"],
                name="submissions_submiss_53a66b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="omrdetectedanswer",
            index=models.Index(
                fields=["recognition_run", "question_number"],
                name="submissions_recogni_aff67e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="omrdetectedanswer",
            constraint=models.UniqueConstraint(
                fields=("recognition_run", "question_number"),
                name="uniq_omr_detected_answer_run_question",
            ),
        ),
        migrations.AddIndex(
            model_name="omrstudentmatch",
            index=models.Index(
                fields=["tenant", "submission", "is_current"],
                name="submissions_tenant__54de0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="omrstudentmatch",
            index=models.Index(
                fields=["tenant", "enrollment_id", "matched_at"],
                name="submissions_tenant__35d63f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="omrstudentmatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("submission",),
                name="uniq_current_omr_student_match",
            ),
        ),
    ]
