# Generated by Django 5.2.9 on 2026-02-12 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_user_phone_and_more"),
        ("submissions", "0006_make_submissions_tenant_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["tenant", "created_at"], name="submissions_tenant__da4eb9_idx"
            ),
        ),
    ]
