# Generated by Django 5.2.16 on 2026-08-23 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_tenant_controls_messaging_activation"),
        ("submissions", "0008_submission_enrollment_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_upload_id", models.UUIDField()),
                ("upload_batch_id", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("object_key", models.CharField(max_length=512)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "media_kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                            ("failed", "Failed"),
                            ("removed", "Removed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "upload_started_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_submission_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="submissions.submission",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_media",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "submission", "status"],
                        name="submissions_tenant__29123f_idx",
                    ),
                    models.Index(
                        fields=["submission", "position", "id"],
                        name="submissions_submiss_a33656_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client_upload_id"),
                        name="uniq_submission_media_client_upload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("removed_at__isnull", True)),
                        fields=("submission", "position"),
                        name="uniq_active_submission_media_position",
                    ),
                ],
            },
        ),
    ]
