# Generated by Django 5.2.16 on 2026-08-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_tenant_controls_messaging_activation"),
        ("submissions", "0009_homework_submission_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmrUploadBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exam_id", models.PositiveBigIntegerField()),
                ("session_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("lecture_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("total_count", models.PositiveSmallIntegerField()),
                ("completion_notice_claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omr_upload_batches",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "created_by", "created_at"],
                        name="omr_batch_owner_created_idx",
                    ),
                    models.Index(
                        fields=["tenant", "exam_id", "created_at"],
                        name="omr_batch_exam_created_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OmrUploadBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordinal", models.PositiveSmallIntegerField()),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("received", "Received"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, default="", max_length=64)),
                ("failure_message", models.CharField(blank=True, default="", max_length=300)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="submissions.omruploadbatch",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="omr_upload_batch_item",
                        to="submissions.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
                "indexes": [
                    models.Index(
                        fields=["batch", "admission_status", "ordinal"],
                        name="omr_item_batch_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "ordinal"),
                        name="uniq_omr_batch_item_ordinal",
                    ),
                ],
            },
        ),
    ]
