# Generated by Django 5.2.16 on 2026-09-09 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_tenant_clinic_booking_interval_minutes_and_more'),
        ('submissions', '0011_omr_batch_content_idempotency'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStorageCleanupIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(choices=[('ai', 'AI'), ('storage', 'Storage')], max_length=16)),
                ('object_key', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('cleaned', 'Cleaned')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_storage_cleanup_intents', to='core.tenant')),
            ],
            options={
                'db_table': 'submissions_storage_cleanup_intent',
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='sub_cleanup_tenant_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'bucket', 'object_key'), name='uniq_sub_cleanup_tenant_bucket_key')],
            },
        ),
    ]
