# Generated by Django 5.1.3 on 2026-05-12 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0037_landing_testimonial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicBoardPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_display_name", models.CharField(blank=True, max_length=80)),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        help_text="작성 당시 역할(student/parent/teacher/owner/admin)",
                        max_length=20,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="익명 표시(작성자 본인은 자기 글로 인식 가능, 타인에게는 필명 노출)",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("free", "자유"),
                            ("tip", "공부 팁"),
                            ("story", "수강 이야기"),
                            ("question", "질문"),
                            ("other", "기타"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                (
                    "is_hot",
                    models.BooleanField(
                        default=False,
                        help_text="HOT 뱃지 (좋아요 N개 이상 자동 또는 학원장 수동)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "게시"),
                            ("hidden", "숨김"),
                            ("deleted", "삭제"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=12,
                    ),
                ),
                (
                    "external_visible",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="비로그인 외부 학부모 노출 여부(학원장 toggle)",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="확장 필드: matchup_report_ids 등 cross-attach",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_board_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_public_board_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_board_posts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_board_post",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="landing_pub_tenant__5c9260_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status", "external_visible", "-created_at"],
                        name="landing_pub_tenant__6a176e_idx",
                    ),
                    models.Index(
                        fields=["tenant", "category", "-created_at"],
                        name="landing_pub_tenant__d6ebe3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicPostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("board", "자유게시판"),
                            ("review", "수강후기"),
                            ("reply", "댓글"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField()),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_post_likes",
                        to="core.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_post_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_post_like",
                "indexes": [
                    models.Index(
                        fields=["tenant", "target_kind", "target_id"],
                        name="landing_pub_tenant__717aed_idx",
                    )
                ],
                "unique_together": {("user", "target_kind", "target_id")},
            },
        ),
        migrations.CreateModel(
            name="PublicPostReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("board", "자유게시판"), ("review", "수강후기")],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(db_index=True)),
                ("author_display_name", models.CharField(blank=True, max_length=80)),
                ("author_role", models.CharField(blank=True, max_length=20)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "is_owner_reply",
                    models.BooleanField(
                        default=False, help_text="학원장(owner) 답글 뱃지 — UI에서 강조"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "is_hidden",
                    models.BooleanField(default=False, help_text="학원장 숨김 처리"),
                ),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_post_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_replies",
                        to="landing_public.publicpostreply",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_post_replies",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_post_reply",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "target_kind", "target_id", "created_at"],
                        name="landing_pub_tenant__4df824_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_display_name", models.CharField(blank=True, max_length=80)),
                (
                    "author_role",
                    models.CharField(
                        blank=True,
                        help_text="작성 당시 역할(student/parent)",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="평점 1~5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "grade",
                    models.CharField(
                        blank=True, help_text="학년(예: 고1 / 중2 / N수)", max_length=20
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="과목(예: 통합과학 / 수학 / 영어)",
                        max_length=40,
                    ),
                ),
                (
                    "enrollment_months",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="수강 개월 수(0=미입력)"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="사진 URL 리스트 (max 8 권장)",
                    ),
                ),
                ("cover_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "승인대기"),
                            ("approved", "공개"),
                            ("rejected", "거절"),
                            ("hidden", "숨김"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("is_pinned", models.BooleanField(db_index=True, default=False)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="수강 이력 검증 (등록DB 매칭 또는 학원장 수동)",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("reply_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_public_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_reviews",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_review",
                "ordering": ["-is_pinned", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"],
                        name="landing_pub_tenant__b4bdf1_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="landing_pub_tenant__2cfd62_idx",
                    ),
                    models.Index(
                        fields=["tenant", "rating"],
                        name="landing_pub_tenant__422e3d_idx",
                    ),
                ],
            },
        ),
    ]
