# Generated by Django 5.1.3 on 2026-05-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_video_session_limits"),
        ("landing_public", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("board", "자유게시판"),
                            ("review", "수강후기"),
                            ("reply", "댓글"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(db_index=True)),
                (
                    "reporter_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="비로그인 신고자 IP — 중복 신고/스팸 차단용",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "광고/스팸"),
                            ("abuse", "욕설/비방"),
                            ("false", "허위/조작"),
                            ("copyright", "저작권 침해"),
                            ("privacy", "개인정보 노출"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="추가 설명(선택)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "처리대기"),
                            ("reviewed", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="학원장이 취한 조치(예: hidden/rejected/dismissed)",
                        max_length=40,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        help_text="신고자(비로그인은 null)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_reports",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-created_at"],
                        name="landing_pub_tenant__50006a_idx",
                    ),
                    models.Index(
                        fields=["tenant", "target_kind", "target_id"],
                        name="landing_pub_tenant__e4605f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicUserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landing_public_block_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_public_blocked_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_user_blocks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_user_block",
                "indexes": [
                    models.Index(
                        fields=["tenant", "blocked_user"],
                        name="landing_pub_tenant__c2ad49_idx",
                    )
                ],
                "unique_together": {("tenant", "blocked_user")},
            },
        ),
    ]
