# Generated by Django 5.1.3 on 2026-05-12 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_tenant_pass_fail_labels"),
        ("landing_public", "0002_publicreport_publicuserblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicExamShowcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_id_ref",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="원본 Exam.id (참조용, FK 아님 — exam 삭제 후에도 snapshot 유지)",
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="예: 2025 중간 통합과학 — 고1 결과", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="학원장 코멘트 (선택)"
                    ),
                ),
                (
                    "anonymization_mode",
                    models.CharField(
                        choices=[
                            ("initial", "성+○○ 마스킹"),
                            ("phone_last4", "이름+전번 뒷자리"),
                            ("pseudonym", "익명 ID"),
                        ],
                        default="initial",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("published", "공개"),
                            ("expired", "기간 만료 (요약만 노출)"),
                            ("hidden", "비공개"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_until",
                    models.DateField(
                        blank=True,
                        help_text="외부 상세 노출 종료 날짜. past 시 카드 요약만 노출. null=영구 노출.",
                        null=True,
                    ),
                ),
                ("rows", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot_at",
                    models.DateTimeField(
                        blank=True, help_text="snapshot 생성 시각", null=True
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_public_exam_showcases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_exam_showcases",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "landing_public_exam_showcase",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "-published_at"],
                        name="landing_pub_tenant__43f200_idx",
                    ),
                    models.Index(
                        fields=["tenant", "exam_id_ref"],
                        name="landing_pub_tenant__c99e0e_idx",
                    ),
                ],
            },
        ),
    ]
