# Generated by Django 5.1.3 on 2026-05-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing_public", "0005_like_unique_tenant"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="publicmatchupshowcase",
            new_name="landing_pub_tenant__33b2f5_idx",
            old_name="lp_mshow_tn_st_pa_idx",
        ),
        migrations.RenameIndex(
            model_name="publicmatchupshowcase",
            new_name="landing_pub_tenant__ae698a_idx",
            old_name="lp_mshow_tn_hr_idx",
        ),
    ]
