# Generated by Django 5.2.17 on 2026-10-02 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_account_notice_credentials"),
        ("landing_public", "0008_problem_review_legacy_publication_compat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicResourcePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_display_name", models.CharField(max_length=100)),
                ("request_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "category",
                    models.CharField(
                        choices=[("matchup", "매치업"), ("analysis", "분석자료")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("published", "게시됨"), ("deleted", "삭제됨")],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PublicResourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                ("is_ready", models.BooleanField(default=False)),
                ("storage_key", models.CharField(max_length=500, unique=True)),
                ("filename", models.CharField(max_length=200)),
                ("extension", models.CharField(max_length=5)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="landing_public.publicresourcepost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicResourceBoardAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publisher_one",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_resource_access_one",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher_two",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_resource_access_two",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("publisher_one__isnull", True),
                            ("publisher_two__isnull", True),
                            models.Q(
                                ("publisher_one", models.F("publisher_two")),
                                _negated=True,
                            ),
                            _connector="OR",
                        ),
                        name="resource_publishers_distinct",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="publicresourcepost",
            index=models.Index(
                fields=["tenant", "status", "category", "-created_at"],
                name="resource_public_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicresourcepost",
            constraint=models.UniqueConstraint(
                fields=("tenant", "request_id"), name="resource_request_unique"
            ),
        ),
    ]
