# Generated by Django 5.2.16 on 2026-10-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_public", "0009_publicresourcepost_publicresourcefile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicresourcefile",
            name="position",
            field=models.PositiveSmallIntegerField(default=0, db_default=0),
        ),
        migrations.AddField(
            model_name="publicresourcefile",
            name="reader_data",
            field=models.JSONField(blank=True, default=dict, db_default={}),
        ),
        migrations.AddField(
            model_name="publicresourcefile",
            name="reader_object_keys",
            field=models.JSONField(blank=True, default=list, db_default=[]),
        ),
        migrations.AddField(
            model_name="publicresourcefile",
            name="reader_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publicresourcefile",
            name="reader_status",
            field=models.CharField(blank=True, default="", db_default="", max_length=12),
        ),
        migrations.AddField(
            model_name="publicresourcefile",
            name="reader_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
